/* Sprint 3B: pure Workforce Deployment v2 authority. */
"use strict";
const assert = require("assert"); const fs = require("fs"); const path = require("path"); global.window = global;
const load = (file) => require(path.join(__dirname, "..", file)); ["js/data/schema.js", "js/data/datasetRegistry.js", "js/masters/branchMaster.js", "js/masters/employeeMaster.js", "js/masters/workforceDeployment.js"].forEach(load);
const Authority = BancaTrackerWorkforceDeployment; const csv = fs.readFileSync(path.join(__dirname, "fixtures", "workforce-deployment-v2", "valid-many-to-many.csv"), "utf8").trim().split(/\r?\n/); const headers = csv.shift().split(","); const fixture = csv.map((line) => Object.fromEntries(headers.map((header, index) => [header, line.split(",")[index] || ""])));
const employee = (employeeId, designation = "Executive", overrides = {}) => ({ employeeId, employeeName: employeeId, designation, employmentStatus: "ACTIVE", dateOfJoining: "2020-01-01", exitDate: null, ...overrides });
const branch = (bankId, branchCode, overrides = {}) => ({ branchId: `${bankId}:${branchCode}`, bankId, branchCode, active: true, validFrom: null, validTo: null, ...overrides });
const employees = [employee("RM001", "Relationship Manager", { role: "RM" }), employee("USM001", "USM"), employee("EXEC001", "Executive"), employee("RM002", "Relationship Manager")]; const branches = [branch("BANK_A", "001"), branch("BANK_A", "002")]; const hasCode = (result, code) => result.findings.some((finding) => finding.code === code);
let prepared = Authority.prepareDataset(fixture, "DEPLOYMENT:3B", employees, branches); assert.strictEqual(prepared.valid, true); assert.strictEqual(prepared.records[0].branchId, "BANK_A:001"); assert.strictEqual(prepared.records[0].recordId, "DEPLOYMENT:3B:RM001:BANK_A:001:PRIMARY:2025-01-01"); assert.strictEqual(prepared.records[1].deploymentType, "SUPPORT"); assert.strictEqual(prepared.records.length, 4, "One employee can cover many branches and a branch can have PRIMARY plus supports.");
prepared = Authority.prepareDataset([{ "EMPLOYEE ID": "EXEC001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-01-01" }], "DEPLOYMENT:3B", employees, branches); assert.strictEqual(prepared.valid, true, "Arbitrary designation and no legacy role remain eligible.");
prepared = Authority.prepareDataset([{ "EMPLOYEE ID": "USM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "SUPPORT", "VALID FROM": "2025-01-01" }, { "EMPLOYEE ID": "EXEC001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "SUPPORT", "VALID FROM": "2025-01-01" }], "DEPLOYMENT:3B", employees, branches); assert.strictEqual(prepared.valid, true, "Concurrent SUPPORT deployments are valid.");
prepared = Authority.prepareDataset([{ "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-01-01", "VALID TO": "2025-03-31" }, { "EMPLOYEE ID": "RM002", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-03-31" }], "DEPLOYMENT:3B", employees, branches); assert.ok(hasCode(prepared, "DEPLOYMENT_V2_BRANCH_PRIMARY_OVERLAP"), "Inclusive shared boundary overlaps.");
prepared = Authority.prepareDataset([{ "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-01-01", "VALID TO": "2025-03-31" }, { "EMPLOYEE ID": "RM002", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-04-01" }], "DEPLOYMENT:3B", employees, branches); assert.strictEqual(prepared.valid, true, "Successor begins after inclusive end date.");
prepared = Authority.prepareDataset([{ "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-01-01" }, { "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "SUPPORT", "VALID FROM": "2025-02-01" }], "DEPLOYMENT:3B", employees, branches); assert.ok(hasCode(prepared, "DEPLOYMENT_V2_EMPLOYEE_BRANCH_OVERLAP"), "An employee cannot concurrently hold contradictory deployment types for one branch.");
const invalidCases = [
  [{ "EMPLOYEE ID": "", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-01-01" }, "DEPLOYMENT_V2_EMPLOYEE_ID_MISSING"],
  [{ "EMPLOYEE ID": "RM001", "BANK ID": "", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-01-01" }, "DEPLOYMENT_V2_BRANCH_ID_MISSING"],
  [{ "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "", "VALID FROM": "2025-01-01" }, "DEPLOYMENT_V2_TYPE_MISSING"],
  [{ "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-01-01" }, "DEPLOYMENT_V2_RELATIONSHIP_DUPLICATE"],
  [{ "EMPLOYEE ID": "UNKNOWN", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "SUPPORT", "VALID FROM": "2025-01-01" }, "DEPLOYMENT_V2_EMPLOYEE_UNMAPPED"],
  [{ "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "999", "DEPLOYMENT TYPE": "SUPPORT", "VALID FROM": "2025-01-01" }, "DEPLOYMENT_V2_BRANCH_UNMAPPED"],
  [{ "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "OWNER", "VALID FROM": "2025-01-01" }, "DEPLOYMENT_V2_TYPE_INVALID"],
  [{ "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "" }, "DEPLOYMENT_V2_VALID_FROM_MISSING"],
  [{ "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-02-30" }, "DEPLOYMENT_V2_DATE_INVALID"],
  [{ "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-02-02", "VALID TO": "2025-02-01" }, "DEPLOYMENT_V2_DATE_ORDER_INVALID"],
];
invalidCases.forEach(([row, code]) => { const rows = code === "DEPLOYMENT_V2_RELATIONSHIP_DUPLICATE" ? [row, row] : [row]; assert.ok(hasCode(Authority.prepareDataset(rows, "DEPLOYMENT:3B", employees, branches), code), `Expected ${code}`); });
prepared = Authority.prepareDataset([{ "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2019-12-31" }], "DEPLOYMENT:3B", employees, branches); assert.ok(hasCode(prepared, "DEPLOYMENT_V2_EMPLOYMENT_RANGE_CONFLICT"));
prepared = Authority.prepareDataset([{ "EMPLOYEE ID": "RM001", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-01-01" }], "DEPLOYMENT:3B", [employee("RM001", "RM", { dateOfJoining: null })], branches); assert.ok(hasCode(prepared, "DEPLOYMENT_V2_EMPLOYMENT_BOUNDARY_UNVERIFIED")); assert.ok(hasCode(prepared, "DEPLOYMENT_V2_BRANCH_BOUNDARY_UNVERIFIED"));
assert.strictEqual(Object.keys(prepared.records[0]).some((key) => /manager|premium|attribution|role/i.test(key)), false, "Authority introduces no hierarchy or attribution output.");
console.log("Sprint 3B Workforce Deployment tests passed: many-to-many coverage, temporal validation, dependency boundaries, and no attribution.");
