/* Step 4Z: Commercial Driver Analysis UI integration. */
"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const childProcess = require("child_process");
class Element { constructor() { this.innerHTML = ""; this.textContent = ""; this.value = ""; this.disabled = false; this.hidden = false; this.listeners = {}; } addEventListener(type, handler) { this.listeners[type] = handler; } }
const elements = {}; global.window = global; global.document = { getElementById(id) { return elements[id] || (elements[id] = new Element()); } };
const root = path.join(__dirname, ".."); const load = (file) => require(path.join(root, file));
load("js/config.js"); load("js/utilities.js"); load("js/analytics/commercialExecutionStatus.js");
const periodContext = { status: "READY", availablePeriods: ["2026-07", "2026-08"], availableFinancialYears: ["FY2026-27"], latestAvailablePeriod: "2026-08", latestActualPeriod: "2026-08", defaultSelectedPeriod: "2026-08" };
const summary = { actualPremium: 30, budget: 100, potential: 200, achievementPct: 30, budgetGap: -70, potentialPenetrationPct: 15, budgetPresentCount: 1, budgetMissingCount: 0, potentialPresentCount: 1, potentialMissingCount: 0, coverageStatus: "COMPLETE" };
global.BancaTrackerCommercialRollups = { buildPeriodContext() { return periodContext; }, getFinancialYear() { return "FY2026-27"; }, buildRollup() { return { status: "READY", summary, diagnostics: {}, rows: [{ key: "A", label: "Same label", ...summary }] }; } };
global.BancaTrackerCore = { state: { factData: [{ monthKey: "2026-08", day: 10, premium: 30 }], commercialPerformance: { status: "READY", rows: [{ periodKey: "2026-08" }] } } }; global.BancaTrackerLiveGeographyAuthority = { getCachedContext() { return { cached: true }; } };
function executionResult(options) { return { status: "READY", selectedPeriod: options.selectedPeriod, dimension: options.dimension, asOfDay: options.asOfDay, observedDays: options.asOfDay, remainingDays: 31 - options.asOfDay, rows: [{ key: options.dimension === "OVERALL" ? "ALL" : "A", label: "Same label", actualToDate: -5, budget: 100, budgetAchievementToDatePct: -5, expectedBudgetToDate: 32, paceGap: -2, averageDailyActual: -1, requiredDailyRunRate: 4, projectedMonthEndActual: -10, projectedAchievementPct: -10, projectedBudgetGap: -110 }], coverage: { budgetPresentCount: 1, budgetMissingCount: 0 }, diagnostics: {} }; }
global.BancaTrackerCommercialExecution = { getDaysInPeriod() { return 31; }, resolveAsOfDay() { return { valid: true, asOfDay: 10 }; }, buildExecution: executionResult };
global.BancaTrackerCommercialExecutionPriority = { buildPriority() { return { rankingApplicable: false, executionPriority: [], referencePriority: [] }; } };
global.BancaTrackerCommercialExecutionDrilldown = { getAllowedDrilldowns() { return ["ZONE"]; }, buildDrilldown() { return { status: "READY", rows: [], reconciliation: { actual: {}, budget: {} }, childDimension: "ZONE" }; } };
let lastComparisonOptions = null;
global.BancaTrackerCommercialComparison = { resolveDefaultPeriods() { return { basePeriod: "2026-07", comparisonPeriod: "2026-08" }; }, buildComparison(options) { lastComparisonOptions = options; return { status: "READY", dimension: options.dimension, rows: [{ key: "A", label: "Same label", base: { actualPremium: 10 }, comparison: { actualPremium: -5 }, changes: { actualChange: -15 } }] }; } };
global.BancaTrackerDailyCommercialComparison = { buildComparison() { return { entities: [] }; } };
const calls = [];
global.BancaTrackerCommercialDriverAnalysis = { getSupportedDriverDimensions() { return ["LOB", "PRODUCT"]; }, buildExecutionDrivers(options) { calls.push({ mode: "execution", options }); return { status: "READY", mode: "EXECUTION_SNAPSHOT", driverDimension: options.driverDimension, rows: [{ key: "__UNMAPPED__", label: "Unmapped", actual: -5, contributionPercent: null }], reconciliation: { parentActual: -5, driverActual: -5, difference: 0 } }; }, buildComparisonDrivers(options) { calls.push({ mode: "comparison", options }); return { status: "READY", mode: "MONTH_COMPARISON", driverDimension: options.driverDimension, rows: [{ key: "PRODUCT_CODE:X", label: "X", baseActual: 10, comparisonActual: -5, change: -15, growthPercent: -150, direction: "DOWN" }], reconciliation: { base: { parent: 10, drivers: 10, difference: 0 }, comparison: { parent: -5, drivers: -5, difference: 0 }, change: { parent: -15, drivers: -15, difference: 0 } } }; } };
load("js/commercialPerformanceUI.js"); const UI = BancaTrackerCommercialPerformanceUI;
UI.renderExecution(periodContext, BancaTrackerCore.state.commercialPerformance, { cached: true }); UI.handleExecutionParentSelect("A", "Same label");
assert.strictEqual(UI.state.execution.driverAnalysis.parentDimension, "BANK"); assert.strictEqual(UI.state.execution.driverAnalysis.parentKey, "A"); assert.strictEqual(calls.at(-1).mode, "execution"); assert.strictEqual(calls.at(-1).options.parentExecutionResult.dimension, "BANK"); assert.strictEqual(calls.at(-1).options.periodKey, "2026-08"); assert.strictEqual(calls.at(-1).options.asOfDay, 10);
assert.match(elements.executionDriverTable.innerHTML, /Unmapped LOB/); assert.match(elements.executionDriverTable.innerHTML, /-\u20b95/); assert.match(elements.executionDriverTable.innerHTML, /N\/A/); assert.match(elements.executionDriverReconciliation.innerHTML, /Parent: -\u20b95/);
UI.handleDriverAnalysisDimensionChange("PRODUCT"); assert.strictEqual(calls.at(-1).options.driverDimension, "PRODUCT"); UI.state.comparison.basePeriod = "2026-07"; UI.state.comparison.comparisonPeriod = "2026-08"; UI.handleDriverAnalysisModeChange("MONTH_COMPARISON"); assert.strictEqual(calls.at(-1).mode, "comparison"); assert.strictEqual(calls.at(-1).options.basePeriod, "2026-07"); assert.strictEqual(calls.at(-1).options.comparisonPeriod, "2026-08"); assert.strictEqual(calls.at(-1).options.parentComparisonResult.dimension, "BANK"); assert.strictEqual(lastComparisonOptions.dimension, "BANK"); assert.match(elements.executionDriverTable.innerHTML, /Degrowth/); assert.match(elements.executionDriverReconciliation.innerHTML, /Comparison/);
global.BancaTrackerCommercialDriverAnalysis.buildExecutionDrivers = () => ({ status: "EMPTY", mode: "EXECUTION_SNAPSHOT", driverDimension: "LOB", rows: [], reconciliation: { parentActual: 0, driverActual: 0, difference: 0 } }); UI.handleDriverAnalysisModeChange("EXECUTION_SNAPSHOT"); assert.match(elements.executionDriverStatus.textContent, /No driver production is available at this execution cutoff/);
const html = fs.readFileSync(path.join(root, "index.html"), "utf8"); const css = fs.readFileSync(path.join(root, "style.css"), "utf8"); const source = fs.readFileSync(path.join(root, "js/commercialPerformanceUI.js"), "utf8");
assert.match(html, /Driver Analysis/); assert.match(html, /for="executionDriverMode">Analysis Mode/); assert.match(html, /for="executionDriverDimension">Driver Dimension/); assert.match(html, /executionDriverStatus[^>]*aria-live="polite"/); assert.ok(html.indexOf("commercialExecutionDrilldown.js") < html.indexOf("commercialDriverAnalysis.js") && html.indexOf("commercialDriverAnalysis.js") < html.indexOf("commercialPerformanceUI.js"));
for (const selector of ["commercial-driver-panel", "commercial-driver-header", "commercial-driver-controls", "commercial-driver-parent", "commercial-driver-table", "commercial-driver-reconciliation", "commercial-driver-empty"]) assert.ok(css.includes(`.${selector}`), selector); assert.match(css, /commercial-driver-table[^}]*overflow-x: auto/); assert.match(css, /commercial-driver-controls[^}]*flex-direction: column/);
assert.match(source, /BancaTrackerCommercialDriverAnalysis\.buildExecutionDrivers/); assert.match(source, /BancaTrackerCommercialDriverAnalysis\.buildComparisonDrivers/); assert.doesNotMatch(source, /getAllowedDrilldowns\(.*(?:PRODUCT|LOB)/);
for (const untouched of ["js/analytics/commercialDriverAnalysis.js", "js/analytics/commercialExecutionDrilldown.js", "js/analytics/commercialExecution.js", "js/analytics/commercialComparison.js", "js/analytics/commercialExecutionStatus.js", "js/analytics/commercialExecutionPriority.js", "js/core.js", "js/target.js"]) assert.strictEqual(childProcess.execFileSync("git", ["diff", "--name-only", "--", untouched], { cwd: root, encoding: "utf8" }).trim(), "", untouched);
assert.match(fs.readFileSync(path.join(root, "README.md"), "utf8"), /Driver Analysis UI presents Step 4Y only/);
console.log("Step 4Z Commercial Driver Analysis UI tests passed: separate authority-only presentation, durable parent selection, compatible parent results, rendering, lifecycle, accessibility, responsiveness, and preservation.");
