/* Step 4G: deterministic browser-facing Sprint 4 acceptance asset chain. */
"use strict";
const assert = require("assert"); const fs = require("fs"); const path = require("path"); const vm = require("vm");
global.window = global;
const root = path.join(__dirname, ".."); const load = (file) => vm.runInThisContext(fs.readFileSync(path.join(root, file), "utf8"), { filename: file }); const fixture = (file) => fs.readFileSync(path.join(__dirname, "fixtures", "business-attribution-v1", file), "utf8");
function csv(text) { const lines = text.trim().split(/\r?\n/); const headers = lines.shift().split(","); return lines.map((line) => Object.fromEntries(headers.map((header, index) => [header, line.split(",")[index] || ""]))); }
["js/data/schema.js", "js/data/datasetRegistry.js", "js/masters/employeeMaster.js", "js/masters/directReportingHierarchy.js", "js/masters/branchMaster.js", "js/masters/workforceDeployment.js", "js/enrichment/businessAttribution.js", "js/enrichment/temporalBusinessAttributionResolver.js", "js/enrichment/directHierarchyResolver.js", "js/analytics/businessAttributionReconciliation.js", "js/analytics/businessAttributionHierarchyRollup.js"].forEach(load);
const employeePrepared = BancaTrackerEmployeeMaster.prepareDataset(csv(fixture("employee-master-v2.csv")), "EMPLOYEE:4G"); assert.strictEqual(employeePrepared.valid, true, JSON.stringify(employeePrepared.findings)); const employees = employeePrepared.records;
const hierarchyPrepared = BancaTrackerDirectReportingHierarchy.prepareDataset(csv(fixture("direct-hierarchy-v2.csv")), "HIERARCHY:4G", employees); assert.strictEqual(hierarchyPrepared.valid, true); const employeeContext = { status: "READY", records: employees }; const hierarchyContext = { status: "READY", records: hierarchyPrepared.records };
const august = BancaTrackerDirectHierarchyResolver.createContext(employeeContext, hierarchyContext, "2025-08-31"); const october = BancaTrackerDirectHierarchyResolver.createContext(employeeContext, hierarchyContext, "2025-10-31");
const legacyAssignments = csv(fixture("legacy-branch-assignment.csv")).map((row) => ({ branchId: `BANK_A:${row["BRANCH CODE"]}`, rmId: row["RM ID"], active: row.ACTIVE === "TRUE", validFrom: row["VALID FROM"], validTo: row["VALID TO"] || null }));
const nativeDeployment = csv(fixture("native-workforce-deployment-v2.csv")).map((row) => ({ employeeId: row["EMPLOYEE ID"], branchId: `BANK_A:${row["BRANCH CODE"]}`, deploymentType: row["DEPLOYMENT TYPE"], active: true, validFrom: row["VALID FROM"] }));
const canonical = csv(fixture("pr-transactions.csv")).map((row) => ({ recordId: row["RECORD ID"], policyIssuedDate: row["POLICY ISSUED DATE"], premium: Number(row["USGI NET PREMIUM"]), sourceRmId: row["Ba Code"] || null, sourceRmName: row["BA NAME"] || null, branchId: `BANK_A:${row["SUM IMD CODE"]}`, bankId: row.INTERMEDIARY, monthKey: row["POLICY ISSUED DATE"].slice(0, 7), lob: row["LINE OF BUSINESS"], productCode: row["PRODUCT CODE"] }));
const context = { employeeRecords: employees, legacyAssignmentRecords: legacyAssignments }; const detached = BancaTrackerTemporalBusinessAttributionResolver.resolveBatch(canonical, context); assert.strictEqual(detached.results.length, canonical.length); assert.deepStrictEqual(detached.results.map((item) => item.canonicalRecordReference), canonical.map((item) => item.recordId)); const byId = (id) => detached.results.find((item) => item.canonicalRecordReference === id);
assert.deepStrictEqual([byId("R_DIRECT").attributionStatus, byId("R_DIRECT").employeeId, byId("R_DIRECT").evidenceType, byId("R_DIRECT").signedActual], ["ATTRIBUTED_SOURCE_RM_ID", "EMP_SRC", "SOURCE_RM_ID", 100]); assert.strictEqual(byId("R_DESIGNATION").employeeId, "EMP_SRC"); assert.strictEqual(byId("R_NAME_ONLY").employeeId, null); assert.strictEqual(byId("R_UNMAPPED").employeeId, null); assert.ok(byId("R_UNMAPPED").diagnostics.includes("ATTRIBUTION_SOURCE_RM_ID_UNMAPPED")); assert.deepStrictEqual([byId("R_FALLBACK").attributionStatus, byId("R_FALLBACK").employeeId], ["ATTRIBUTED_LEGACY_BRANCH_ASSIGNMENT", "LEGACY_RM"]);
assert.strictEqual(byId("R_BEFORE_JOIN").temporalStatus, "NOT_EFFECTIVE"); assert.strictEqual(byId("R_AFTER_EXIT").temporalStatus, "NOT_EFFECTIVE"); assert.strictEqual(byId("R_UNVERIFIED").temporalStatus, "UNVERIFIED"); assert.deepStrictEqual([byId("R_DIRECT").signedActual, byId("R_UNVERIFIED").signedActual, byId("R_FALLBACK").signedActual], [100, 0, -20]);
const nativeIsolation = BancaTrackerTemporalBusinessAttributionResolver.resolveBatch([canonical.find((item) => item.recordId === "R_DIRECT"), canonical.find((item) => item.recordId === "R_FALLBACK")], { employeeRecords: employees, legacyAssignmentRecords: nativeDeployment }).results; assert.strictEqual(nativeIsolation[0].employeeId, "EMP_SRC"); assert.strictEqual(nativeIsolation[1].employeeId, null);
const reconciliation = BancaTrackerBusinessAttributionReconciliation.reconcile(canonical, detached.results); assert.strictEqual(reconciliation.status, "RECONCILED"); assert.deepStrictEqual([reconciliation.reconciliation.underlyingRecordCount, reconciliation.reconciliation.attributedRecordCount + reconciliation.reconciliation.unattributedRecordCount, reconciliation.reconciliation.underlyingSignedActual, reconciliation.reconciliation.attributedSignedActual + reconciliation.reconciliation.unattributedSignedActual], [canonical.length, canonical.length, 295, 295]); assert.deepStrictEqual([reconciliation.coverage.directSourceAttributedCount, reconciliation.coverage.legacyFallbackAttributedCount, reconciliation.coverage.unmappedSourceIdentityCount, reconciliation.coverage.temporallyNotEffectiveCount, reconciliation.coverage.temporallyUnverifiedCount], [6, 1, 1, 2, 1]); assert.strictEqual(reconciliation.coverage.grossAbsoluteAttributedValueCoveragePercent, 275 / 335 * 100);
for (const selector of [(item) => item.bankId, (item) => item.branchId, (item) => item.monthKey, (item) => item.lob, (item) => item.productCode]) assert.ok(BancaTrackerBusinessAttributionReconciliation.reconcileBy(canonical, detached.results, selector).rows.every((row) => row.reconciliation.complete));
const rollup = BancaTrackerBusinessAttributionHierarchyRollup.buildRollupRecords(detached.results, new Map([["2025-08-31", august], ["2025-10-31", october]])); const direct = rollup.find((item) => item.canonicalRecordReference === "R_DIRECT"); const historical = rollup.filter((item) => ["R_OLD_MANAGER", "R_NEW_MANAGER"].includes(item.canonicalRecordReference)); assert.deepStrictEqual([direct.directOwnerId, direct.directManagerId, direct.signedActual], ["EMP_SRC", "MGR_OLD", 100]); assert.deepStrictEqual(historical.map((item) => item.directManagerId), ["MGR_OLD", "MGR_NEW"]); assert.strictEqual(rollup.find((item) => item.canonicalRecordReference === "R_NO_REL").hierarchyStatus, "NO_RELATIONSHIP"); assert.deepStrictEqual(rollup.find((item) => item.canonicalRecordReference === "R_NAME_ONLY").rollupNodeIds, []); assert.strictEqual(new Set(direct.rollupNodeIds).size, direct.rollupNodeIds.length); assert.strictEqual(BancaTrackerBusinessAttributionHierarchyRollup.validateDirectReconciliation(rollup).directSignedActual, reconciliation.coverage.attributedSignedActual);
assert.strictEqual(BancaTrackerSchema.DATABASE.VERSION, 2); const snapshot = JSON.stringify(canonical); assert.deepStrictEqual(detached, BancaTrackerTemporalBusinessAttributionResolver.resolveBatch(canonical, context)); assert.strictEqual(JSON.stringify(canonical), snapshot);
console.log("Step 4G Business Attribution browser acceptance tests passed: deterministic fixtures, attribution, temporal gates, reconciliation, coverage, dynamic hierarchy, isolation, and persistence boundary.");
