/* Sprint 2E: Legacy fixed-slot projection over Direct Reporting v2. */
"use strict";
const assert = require("assert"); const path = require("path"); global.window = global;
const load = (file) => require(path.join(__dirname, "..", file));
["js/data/schema.js", "js/data/datasetRegistry.js", "js/masters/employeeMaster.js", "js/masters/directReportingHierarchy.js", "js/enrichment/hierarchyResolver.js", "js/enrichment/directHierarchyResolver.js", "js/enrichment/directHierarchyLegacyProjection.js"].forEach(load);
const Employee = BancaTrackerEmployeeMaster; const Authority = BancaTrackerDirectReportingHierarchy; const Resolver = BancaTrackerDirectHierarchyResolver; const Projection = BancaTrackerDirectHierarchyLegacyProjection; const Contract = BancaTrackerDatasetRegistry.HIERARCHY_DATA_CONTRACT;
const employee = (id, designation, role = null, extras = {}) => ({ employeeId: id, employeeName: id, designation, legacyHierarchyRole: Employee.normalizeRole(role), role: Employee.normalizeRole(role), employmentStatus: "ACTIVE", dateOfJoining: "2020-01-01", exitDate: null, ...extras });
const row = (id, manager, from = "2025-01-01", to = "") => ({ "EMPLOYEE ID": id, "MANAGER EMPLOYEE ID": manager || "", "VALID FROM": from, "VALID TO": to });
function context(employees, rows, asOfDate = "2025-08-31") { const records = Authority.prepareDataset(rows, "HIERARCHY:2E", employees).records; return Resolver.createContext({ status: "READY", records: employees }, { status: "READY", contract: { sourceProfile: Contract.PROFILES.DIRECT_REPORTING_V2 }, records }, asOfDate); }

let people = [employee("RM", "Relationship Manager", "RM"), employee("CSM", "Channel Sales Manager", "CSM"), employee("ASM", "Area Sales Manager", "ASM"), employee("ZSM", "Zonal Sales Manager", "ZSM"), employee("NH", "National Head", "NATIONAL_HEAD")];
let direct = context(people, [row("RM", "CSM"), row("CSM", "ASM"), row("ASM", "ZSM"), row("ZSM", "NH"), row("NH", null)]);
let projected = Projection.projectEmployee("RM", direct);
assert.deepStrictEqual({ status: projected.status, rm: projected.rmId, csm: projected.csmId, asm: projected.asmId, zsm: projected.zsmId, nh: projected.nationalHeadId }, { status: "COMPLETE", rm: "RM", csm: "CSM", asm: "ASM", zsm: "ZSM", nh: "NH" });

people = [employee("RM", "RM", "RM"), employee("NH", "Head", "NATIONAL_HEAD")]; direct = context(people, [row("RM", "NH"), row("NH", null)]); projected = Projection.projectEmployee("RM", direct);
assert.deepStrictEqual([projected.rmId, projected.csmId, projected.asmId, projected.zsmId, projected.nationalHeadId], ["RM", null, null, null, "NH"], "Skip levels remain null.");

people = [employee("EXEC", "Executive"), employee("ZSM", "Zonal", "ZSM"), employee("NH", "Head", "NATIONAL_HEAD")]; direct = context(people, [row("EXEC", "ZSM"), row("ZSM", "NH"), row("NH", null)]); projected = Projection.projectEmployee("EXEC", direct);
assert.deepStrictEqual([projected.rmId, projected.zsmId, projected.nationalHeadId], [null, "ZSM", "NH"], "Designation must never infer RM.");
assert.strictEqual(Projection.projectEmployee("ZSM", direct).zsmId, "ZSM"); assert.strictEqual(Projection.projectEmployee("NH", direct).nationalHeadId, "NH");
people = [employee("ASM", "Area Sales Manager", "ASM"), employee("NH", "Head", "NATIONAL_HEAD")]; direct = context(people, [row("ASM", "NH"), row("NH", null)]); assert.strictEqual(Projection.projectEmployee("ASM", direct).asmId, "ASM", "Self can populate ASM.");

people = [employee("ROOT", "Executive")]; direct = context(people, [row("ROOT", null)]); projected = Projection.projectEmployee("ROOT", direct); assert.strictEqual(projected.status, "NONE"); assert.strictEqual(projected.sourceResolutionStatus, "EXPLICIT_ROOT");
people = [employee("E", "Employee"), employee("A1", "Manager", "ASM"), employee("A2", "Manager", "ASM"), employee("ROOT", "Root")]; direct = context(people, [row("E", "A1"), row("A1", "A2"), row("A2", "ROOT"), row("ROOT", null)]); projected = Projection.projectEmployee("E", direct); assert.strictEqual(projected.status, "AMBIGUOUS"); assert.strictEqual(projected.asmId, "A1"); assert.ok(projected.diagnostics.includes("LEGACY_ROLE_DUPLICATE_IN_CHAIN"));
people = [employee("RM", "RM", "RM"), employee("Z", "ZSM", "ZSM"), employee("A", "ASM", "ASM"), employee("NH", "Head", "NATIONAL_HEAD")]; direct = context(people, [row("RM", "Z"), row("Z", "A"), row("A", "NH"), row("NH", null)]); projected = Projection.projectEmployee("RM", direct); assert.ok(projected.diagnostics.includes("LEGACY_ROLE_ORDER_MISMATCH")); assert.strictEqual(projected.asmId, "A");
people = [employee("E", "Employee"), employee("M", "Manager", "ASM")]; direct = context(people, [row("E", "M")]); assert.strictEqual(Projection.projectEmployee("E", direct).status, "PARTIAL"); assert.strictEqual(Projection.projectEmployee("E", direct).sourceResolutionStatus, "CHAIN_INCOMPLETE"); assert.strictEqual(Projection.projectEmployee("M", direct).status, "NO_RELATIONSHIP");
people = [employee("E", "Employee", null, { dateOfJoining: "2026-01-01" }), employee("ROOT", "Head", "NATIONAL_HEAD")]; direct = context(people, [row("E", "ROOT", "2026-01-01"), row("ROOT", null)]); assert.strictEqual(Projection.projectEmployee("E", direct).status, "NOT_EFFECTIVE");
people = [employee("E", "Employee", "RM"), employee("OLD", "Old", "ASM"), employee("NEW", "New", "ZSM"), employee("NH", "Head", "NATIONAL_HEAD")]; const rows = [row("E", "OLD", "2025-01-01", "2025-06-30"), row("E", "NEW", "2025-07-01"), row("OLD", "NH"), row("NEW", "NH"), row("NH", null)]; assert.strictEqual(Projection.projectEmployee("E", context(people, rows, "2025-06-30")).asmId, "OLD"); assert.strictEqual(Projection.projectEmployee("E", context(people, rows, "2025-07-01")).zsmId, "NEW");
direct = context(people, rows, "2025-07-01"); const beforeProjection = JSON.stringify(direct.hierarchyContext.records); const batch = Projection.projectEmployees(direct); assert.strictEqual(batch.diagnostics.projectedEmployeeCount, 4); assert.deepStrictEqual(Projection.projectEmployee("E", direct), Projection.projectEmployee("E", direct), "Projection output is deterministic."); assert.strictEqual(JSON.stringify(direct.hierarchyContext.records), beforeProjection, "Projection must not mutate hierarchy persistence records."); assert.strictEqual(Projection.projectEmployee("E", context([employee("E", "Executive")], [row("E", null)])).rmId, null, "No designation mapping is available.");
const legacyLookup = BancaTrackerHierarchyResolver.buildLookupMaps([employee("L1", "Legacy", "RM"), employee("L2", "Legacy", "NATIONAL_HEAD")], [{ employeeId: "L1", managerId: "L2" }]);
assert.strictEqual(BancaTrackerHierarchyResolver.resolveHierarchy("L1", legacyLookup).rmId, "L1", "Legacy v8.2 resolver remains independently available.");
console.log("Sprint 2E legacy projection tests passed: explicit-role slots, skips, ambiguity, status isolation, history, and batch diagnostics.");
