/* Sprint 1E: Employee Vintage Authority. */
"use strict";
const assert = require("assert"); const path = require("path"); global.window = global;
require(path.join(__dirname, "..", "js/analytics/employeeVintage.js"));
const Vintage = BancaTrackerEmployeeVintage;
const employee = (overrides = {}) => ({ employeeId: "E1", dateOfJoining: "2020-01-15", channelJoinDate: "2021-04-01", designationEffectiveDate: "2023-06-01", employmentStatus: "ACTIVE", exitDate: null, ...overrides });
let result = Vintage.evaluateEmployee(employee(), "2025-01-15");
assert.strictEqual(result.status, "READY");
assert.deepStrictEqual(result.companyVintage, { status: "AVAILABLE", available: true, startDate: "2020-01-15", effectiveEndDate: "2025-01-15", completedDays: 1827, completedMonths: 60, completedYears: 5 });
assert.strictEqual(result.employmentTenure.completedYears, 5, "Employment tenure is the Company Vintage canonical metric.");
assert.strictEqual(result.channelVintage.completedMonths, 45); assert.strictEqual(result.designationVintage.completedMonths, 19);
result = Vintage.evaluateEmployee(employee({ channelJoinDate: null, designationEffectiveDate: null }), "2025-01-15");
assert.strictEqual(result.channelVintage.status, "UNAVAILABLE_SOURCE_DATE"); assert.strictEqual(result.designationVintage.completedDays, null);
result = Vintage.evaluateEmployee(employee({ exitDate: "2026-02-15", employmentStatus: "EXITED" }), "2025-08-31");
assert.strictEqual(result.companyVintage.effectiveEndDate, "2025-08-31"); assert.strictEqual(result.companyVintage.completedDays, 2055);
result = Vintage.evaluateEmployee(employee({ exitDate: "2026-02-15", employmentStatus: "EXITED" }), "2026-08-31");
assert.strictEqual(result.companyVintage.effectiveEndDate, "2026-02-15"); assert.strictEqual(result.companyVintage.completedYears, 6);
assert.strictEqual(Vintage.evaluateEmployee(employee({ exitDate: "2026-02-15" }), "2026-02-15").companyVintage.effectiveEndDate, "2026-02-15");
result = Vintage.evaluateEmployee(employee({ dateOfJoining: "2020-02-29" }), "2021-02-28");
assert.strictEqual(result.companyVintage.completedYears, 1); assert.strictEqual(result.companyVintage.completedDays, 365);
result = Vintage.evaluateEmployee(employee({ dateOfJoining: "2021-01-31" }), "2021-02-28"); assert.strictEqual(result.companyVintage.completedMonths, 1);
result = Vintage.evaluateEmployee(employee({ dateOfJoining: "2025-01-15" }), "2025-01-15"); assert.strictEqual(result.companyVintage.completedDays, 0); assert.strictEqual(result.companyVintage.completedMonths, 0);
result = Vintage.evaluateEmployee(employee({ dateOfJoining: "2025-01-16" }), "2025-01-15"); assert.strictEqual(result.companyVintage.status, "NOT_YET_EFFECTIVE"); assert.strictEqual(result.companyVintage.completedDays, null);
result = Vintage.evaluateEmployee(employee({ dateOfJoining: "2025-02-30" }), "2025-01-15"); assert.strictEqual(result.status, "PARTIAL"); assert.ok(result.diagnostics.includes("EMPLOYEE_VINTAGE_JOIN_DATE_INVALID"));
assert.strictEqual(Vintage.evaluateEmployee(employee(), "15/01/2025").status, "INVALID_AS_OF_DATE");
const batch = Vintage.evaluateEmployees([employee(), employee({ employeeId: "E2", channelJoinDate: null }), employee({ employeeId: "E3", dateOfJoining: "invalid" }), null], "2025-01-15");
assert.strictEqual(batch.diagnostics.evaluatedCount, 4); assert.strictEqual(batch.diagnostics.missingChannelAnchorCount, 1); assert.strictEqual(batch.diagnostics.invalidRecordCount, 2);
assert.strictEqual(batch.results[0].companyVintage.completedDays, Vintage.evaluateEmployee(employee(), "2025-01-15").companyVintage.completedDays, "Results must depend only on supplied dates, not the system clock.");
console.log("Sprint 1E Employee Vintage tests passed: explicit as-of dates, calendar-safe tenure, exit capping, missing/invalid anchors, and batch diagnostics.");
