/* Sprint 2F: Browser-facing Direct Reporting v2 lifecycle acceptance. */
"use strict";
const assert = require("assert"); const fs = require("fs"); const path = require("path"); global.window = global;
const load = (file) => require(path.join(__dirname, "..", file)); const fixture = (file) => fs.readFileSync(path.join(__dirname, "fixtures", "direct-hierarchy-v2", file), "utf8");
["js/csvProcessor.js", "js/data/schema.js", "js/data/datasetRegistry.js", "js/masters/employeeMaster.js", "js/masters/directReportingHierarchy.js", "js/masters/hierarchyMaster.js", "js/enrichment/hierarchyResolver.js", "js/enrichment/directHierarchyResolver.js", "js/enrichment/directHierarchyLegacyProjection.js", "js/masterDataImport.js"].forEach(load);
const Importer = BancaTrackerMasterDataImport; const Resolver = BancaTrackerDirectHierarchyResolver; const Projection = BancaTrackerDirectHierarchyLegacyProjection; const Contract = BancaTrackerDatasetRegistry.HIERARCHY_DATA_CONTRACT;
const employee = (employeeId, designation, role = null) => ({ employeeId, employeeName: employeeId, designation, legacyHierarchyRole: BancaTrackerEmployeeMaster.normalizeRole(role), role: BancaTrackerEmployeeMaster.normalizeRole(role), employmentStatus: "ACTIVE", dateOfJoining: "2020-01-01", exitDate: null, active: true });
const employees = [employee("RM001", "Relationship Manager", "RM"), employee("CSM001", "Channel Sales Manager", "CSM"), employee("ASM001", "Area Sales Manager", "ASM"), employee("ZSM001", "Zonal Sales Manager", "ZSM"), employee("NH001", "National Head", "NATIONAL_HEAD"), employee("RM_SKIP", "Relationship Manager", "RM"), employee("EXEC001", "Executive"), employee("COORD001", "Coordinator"), employee("MT001", "Management Trainee"), employee("USM001", "Unit Sales Manager"), employee("EMP001", "Executive"), employee("MGR001", "Manager", "ASM"), employee("MGR002", "Manager", "ZSM"), employee("EXEC002", "Executive"), employee("ROOT002", "Business Head"), employee("UNMAPPED001", "Coordinator"), employee("BAD_UNKNOWN", "Executive"), employee("BAD_SELF", "Executive"), employee("BAD_OVERLAP", "Executive"), employee("BAD_DATE", "Executive"), employee("CYCLE001", "Executive"), employee("CYCLE002", "Executive"), employee("DUP001", "Executive")];
const legacyEmployees = [employee("LEGACY_NH", "National Head", "NATIONAL_HEAD"), employee("LEGACY_ZSM", "Zonal Sales Manager", "ZSM"), employee("LEGACY_ASM", "Area Sales Manager", "ASM"), employee("LEGACY_CSM", "Channel Sales Manager", "CSM"), employee("LEGACY_RM", "Relationship Manager", "RM")];
class MemoryRepository {
  constructor() { this.datasets = new Map(); this.records = new Map(); this.active = new Map(); this.versions = new Map(); }
  async getActiveEmployeeMasterContext() { return { status: "READY", records: employees, diagnostics: [] }; }
  async getActiveMasterRecords(type) { return type === "EMPLOYEE_MASTER" ? legacyEmployees : this.records.get(this.active.get(type)) || []; }
  async stageDataset(metadata) { const version = (this.versions.get(metadata.datasetType) || 0) + 1; this.versions.set(metadata.datasetType, version); const dataset = { ...metadata, datasetId: `${metadata.datasetType}:${version}`, datasetVersion: version, status: "STAGED" }; this.datasets.set(dataset.datasetId, dataset); return dataset; }
  async saveStagedMasterRecords(datasetId, records) { this.records.set(datasetId, records); }
  async activateDataset(datasetId) { const dataset = this.datasets.get(datasetId); const previousDatasetId = this.active.get(dataset.datasetType) || null; if (previousDatasetId) this.datasets.get(previousDatasetId).status = "SUPERSEDED"; dataset.status = "ACTIVE"; this.active.set(dataset.datasetType, datasetId); return { success: true, datasetId, previousDatasetId }; }
  async markDatasetFailed(datasetId) { this.datasets.get(datasetId).status = "FAILED"; }
  async getActiveHierarchyContext() { const dataset = this.datasets.get(this.active.get("HIERARCHY")); return BancaTrackerDirectReportingHierarchy.adaptPersistedDataset(dataset, await this.getActiveMasterRecords("HIERARCHY")); }
  async getActiveDirectHierarchyResolutionContext(asOfDate) { return Resolver.createContext(await this.getActiveEmployeeMasterContext(), await this.getActiveHierarchyContext(), asOfDate); }
}
const preview = (repository, text, fileName) => Importer.prepareImport("HIERARCHY", Importer.parseText(text), { repository, fileName });

(async function () {
  assert.strictEqual(BancaTrackerSchema.DATABASE.VERSION, 2, "Sprint 2 must not change IndexedDB version.");
  const repository = new MemoryRepository();
  const nativePreview = await preview(repository, fixture("valid-native-v2.csv"), "valid-native-v2.csv");
  assert.strictEqual(nativePreview.valid, true); assert.strictEqual(nativePreview.hierarchyProfile.sourceProfile, Contract.PROFILES.DIRECT_REPORTING_V2);
  const nativeCommit = await Importer.commitImport(nativePreview, { repository }); assert.strictEqual(nativeCommit.dataset.status, "ACTIVE"); assert.strictEqual(nativeCommit.dataset.metadata.dataContract.sourceProfile, Contract.PROFILES.DIRECT_REPORTING_V2);
  const hierarchyContext = await repository.getActiveHierarchyContext(); assert.strictEqual(hierarchyContext.status, "READY"); assert.strictEqual(hierarchyContext.contract.sourceProfile, Contract.PROFILES.DIRECT_REPORTING_V2); assert.ok(hierarchyContext.records.every((record) => record.managerEmployeeId !== undefined));
  const august = await repository.getActiveDirectHierarchyResolutionContext("2025-08-31"); const october = await repository.getActiveDirectHierarchyResolutionContext("2025-10-31");
  assert.strictEqual(august.status, "READY_PARTIAL"); assert.deepStrictEqual(august.roots, ["NH001", "ROOT002"]); assert.strictEqual(Resolver.getManager("EMP001", august), "MGR001"); assert.strictEqual(Resolver.getManager("EMP001", october), "MGR002");
  assert.deepStrictEqual(Resolver.getAncestors("RM_SKIP", august), ["NH001"]); assert.strictEqual(Resolver.resolveEmployee("UNMAPPED001", august).status, "NO_RELATIONSHIP"); assert.deepStrictEqual(Resolver.getDirectReports("MGR001", august), ["EMP001"]); assert.deepStrictEqual(Resolver.getDirectReports("MGR001", october), []); assert.ok(Resolver.getDescendants("NH001", august).includes("MT001")); assert.ok(Resolver.getRollupMembers("NH001", august, { includeSelf: true }).includes("NH001"));
  const skipProjection = Projection.projectEmployee("RM_SKIP", august); assert.deepStrictEqual([skipProjection.rmId, skipProjection.csmId, skipProjection.asmId, skipProjection.zsmId, skipProjection.nationalHeadId], ["RM_SKIP", null, null, null, "NH001"]); assert.strictEqual(Projection.projectEmployee("EXEC001", august).rmId, null, "Designation must not infer legacy role slots.");
  const persisted = repository.records.get(nativeCommit.dataset.datasetId); ["reportingChain", "reportingDepth", "rootEmployeeId", "descendants", "rollupMembers", "asOfDate", "rmId", "csmId", "asmId", "zsmId", "nationalHeadId"].forEach((field) => assert.ok(persisted.every((record) => !(field in record)), `${field} must remain runtime-only.`));
  const activeBeforeInvalid = repository.active.get("HIERARCHY"); const invalidPreview = await preview(repository, fixture("invalid-native-v2.csv"), "invalid-native-v2.csv"); assert.strictEqual(invalidPreview.valid, false); ["HIERARCHY_V2_MANAGER_UNMAPPED", "HIERARCHY_V2_SELF_REFERENCE", "HIERARCHY_V2_RELATIONSHIP_OVERLAP", "HIERARCHY_V2_DATE_ORDER_INVALID", "HIERARCHY_V2_CYCLE_DETECTED", "HIERARCHY_V2_RELATIONSHIP_DUPLICATE"].forEach((code) => assert.ok(invalidPreview.findings.some((finding) => finding.code === code), `Expected ${code}`)); await assert.rejects(() => Importer.commitImport(invalidPreview, { repository }), /valid preview/); assert.strictEqual(repository.active.get("HIERARCHY"), activeBeforeInvalid, "Invalid replacement cannot displace active hierarchy.");
  const legacyPreview = await preview(repository, fixture("legacy-v8.2-hierarchy.csv"), "legacy-v8.2-hierarchy.csv"); assert.strictEqual(legacyPreview.valid, true); assert.strictEqual(legacyPreview.hierarchyProfile.sourceProfile, Contract.PROFILES.LEGACY_V1); const legacyCommit = await Importer.commitImport(legacyPreview, { repository }); const legacyContext = await repository.getActiveHierarchyContext(); assert.strictEqual(legacyContext.status, "LEGACY_COMPATIBILITY"); assert.strictEqual(legacyContext.contract.sourceProfile, Contract.PROFILES.LEGACY_V1); assert.strictEqual(legacyCommit.dataset.metadata.dataContract.version, 1);
  const metadataLess = BancaTrackerDirectReportingHierarchy.adaptPersistedDataset({ datasetId: "HIERARCHY:LEGACY", metadata: null }, legacyCommit.records); assert.strictEqual(metadataLess.status, "LEGACY_COMPATIBILITY"); assert.strictEqual(metadataLess.contract.sourceProfile, Contract.PROFILES.LEGACY_V1_ASSUMED);
  console.log("Sprint 2F browser acceptance tests passed: v2 lifecycle, temporal graph, projection, legacy isolation, replacement safety, and persistence hygiene.");
})().catch((error) => { console.error(error); process.exit(1); });
