/* Sprint 3D: pure temporal Workforce Deployment resolution. */
"use strict";
const assert = require("assert"); const path = require("path"); global.window = global;
const load = (file) => require(path.join(__dirname, "..", file)); ["js/data/schema.js", "js/data/datasetRegistry.js", "js/masters/branchMaster.js", "js/masters/employeeMaster.js", "js/masters/workforceDeployment.js", "js/enrichment/workforceDeploymentResolver.js"].forEach(load);
const Authority = BancaTrackerWorkforceDeployment; const Resolver = BancaTrackerWorkforceDeploymentResolver; const Contract = BancaTrackerDatasetRegistry.WORKFORCE_DEPLOYMENT_DATA_CONTRACT;
const row = (employeeId, branchCode, deploymentType, validFrom = "2025-01-01", validTo = "") => ({ "EMPLOYEE ID": employeeId, "BANK ID": "BANK_A", "BRANCH CODE": branchCode, "DEPLOYMENT TYPE": deploymentType, "VALID FROM": validFrom, "VALID TO": validTo });
const context = (rows, asOfDate) => Resolver.createContext({ status: "READY", contract: { sourceProfile: Contract.PROFILES.WORKFORCE_DEPLOYMENT_V2 }, records: Authority.prepareDataset(rows, "DEPLOYMENT:3D", [], []).records }, asOfDate);
const rows = [row("EMP001", "001", "PRIMARY", "2025-01-01", "2025-09-30"), row("EMP001", "002", "PRIMARY", "2025-10-01"), row("EMP001", "003", "SUPPORT"), row("EMP002", "001", "SUPPORT"), row("EMP003", "001", "SUPPORT"), row("SUPPORT_ONLY", "004", "SUPPORT")];
let august = context(rows, "2025-08-31"); let october = context(rows, "2025-10-31"); assert.strictEqual(august.status, "READY"); assert.strictEqual(Resolver.createContext({ status: "READY", contract: { sourceProfile: Contract.PROFILES.WORKFORCE_DEPLOYMENT_V2 }, records: [] }, "").status, "INVALID_AS_OF_DATE"); assert.strictEqual(Resolver.createContext({ status: "READY", contract: { sourceProfile: Contract.PROFILES.WORKFORCE_DEPLOYMENT_V2 }, records: [] }, "31/08/2025").status, "INVALID_AS_OF_DATE");
assert.strictEqual(Resolver.createContext({ status: "ABSENT", records: [] }, "2025-08-31").status, "ABSENT"); assert.strictEqual(Resolver.createContext({ status: "LEGACY_COMPATIBILITY", records: [] }, "2025-08-31").status, "LEGACY_COMPATIBILITY"); assert.strictEqual(Resolver.createContext({ status: "UNSUPPORTED_CONTRACT", records: [] }, "2025-08-31").status, "UNSUPPORTED_CONTRACT");
assert.deepStrictEqual(Resolver.resolveEmployee("EMP001", august).deployments.map((item) => item.branchId), ["BANK_A:001", "BANK_A:003"]); assert.deepStrictEqual(Resolver.resolveEmployee("EMP001", october).deployments.map((item) => item.branchId), ["BANK_A:002", "BANK_A:003"]); assert.strictEqual(Resolver.resolveEmployee("NONE", august).status, "NO_DEPLOYMENT"); assert.deepStrictEqual(Resolver.resolveBranch("BANK_A:001", august).support.map((item) => item.employeeId), ["EMP002", "EMP003"]); assert.strictEqual(Resolver.getPrimary("BANK_A:001", august).deployment.employeeId, "EMP001"); assert.strictEqual(Resolver.getPrimary("BANK_A:004", august).deployment, null); assert.deepStrictEqual(Resolver.getSupport("BANK_A:001", august).map((item) => item.employeeId), ["EMP002", "EMP003"]); assert.strictEqual(Resolver.resolveBranch("BANK_A:004", august).primary, null, "Support-only branch has no fabricated primary.");
assert.strictEqual(Resolver.resolveBranch("BANK_A:001", context(rows, "2025-01-01")).primary.employeeId, "EMP001", "VALID FROM is inclusive."); assert.strictEqual(Resolver.resolveBranch("BANK_A:001", context(rows, "2025-09-30")).primary.employeeId, "EMP001", "VALID TO is inclusive."); assert.strictEqual(Resolver.resolveBranch("BANK_A:001", context(rows, "2024-12-31")).status, "NO_DEPLOYMENT"); assert.strictEqual(Resolver.resolveBranch("BANK_A:001", context(rows, "2025-10-01")).primary, null); assert.strictEqual(Resolver.resolveBranch("BANK_A:002", context(rows, "2030-01-01")).primary.employeeId, "EMP001", "Open-ended row remains effective."); assert.strictEqual(august.coverage.employeesWithMultipleEffectiveBranches, 1); assert.strictEqual(august.coverage.branchesWithPrimary, 1); assert.strictEqual(august.coverage.branchesWithSupport, 3);
const corrupt = context([row("P1", "009", "PRIMARY"), row("P2", "009", "PRIMARY")], "2025-08-31"); assert.strictEqual(corrupt.status, "INVALID"); assert.strictEqual(Resolver.resolveBranch("BANK_A:009", corrupt).status, "PRIMARY_CONFLICT"); assert.strictEqual(Resolver.getPrimary("BANK_A:009", corrupt).deployment, null, "Corrupt primary conflict is never chosen arbitrarily.");
assert.strictEqual(Object.keys(Resolver.resolveEmployee("EMP001", august).deployments[0]).some((key) => /premium|attribution|manager|owner|credit/i.test(key)), false, "Resolver exposes no business attribution or hierarchy fields."); assert.strictEqual(typeof BancaTrackerAssignmentResolver, "undefined", "Native resolver does not load legacy RM resolver."); assert.strictEqual(BancaTrackerSchema.DATABASE.VERSION, 2);
(async function () {
  let dbState = { activeId: null, datasets: new Map(), records: [] }; global.BancaTrackerIndexedDb = { async get(store, key) { if (store === BancaTrackerSchema.STORES.APP_METADATA) return key === "activeDataset:BRANCH_ASSIGNMENT" && dbState.activeId ? { key, value: dbState.activeId } : null; if (store === BancaTrackerSchema.STORES.DATASETS) return dbState.datasets.get(key) || null; return null; }, async getAllByIndex(store, index, value) { return store === BancaTrackerSchema.STORES.BRANCH_ASSIGNMENTS && index === "datasetId" && value === dbState.activeId ? dbState.records : []; } };
  load("js/data/repository.js"); const dataset = { datasetId: "BRANCH_ASSIGNMENT:3D", status: "ACTIVE", metadata: { dataContract: { name: Contract.NAME, version: 2, sourceProfile: Contract.PROFILES.WORKFORCE_DEPLOYMENT_V2 } } }; const persisted = Authority.prepareDataset(rows, dataset.datasetId, [], []).records.map(Authority.toPersistedRecord); dbState = { activeId: dataset.datasetId, datasets: new Map([[dataset.datasetId, dataset]]), records: persisted }; assert.strictEqual((await BancaTrackerRepository.getActiveWorkforceDeploymentResolutionContext("2025-08-31")).status, "READY", "Repository convenience delegates only to the pure resolver.");
  console.log("Sprint 3D Workforce Deployment resolution tests passed: explicit dates, many-to-many indexes, primary/support semantics, history, conflict safety, and isolation.");
})().catch((error) => { console.error(error); process.exit(1); });
