/* Step 5C: governed workforce slices, diagnostics and scoped reconciliation. */
"use strict";
const assert = require("assert"); const fs = require("fs"); const path = require("path"); const vm = require("vm"); global.window = global;
vm.runInThisContext(fs.readFileSync(path.join(__dirname, "..", "js/analytics/workforcePerformance.js"), "utf8"), { filename: "workforcePerformance.js" }); const Analytics = BancaTrackerWorkforcePerformance;
const records = [
  { recordId: "A", premium: 100, bankId: "BANK_A", branchId: "BR_1", zoneId: "ZONE_1", stateId: "STATE_1", monthKey: "2025-08", fy: "FY26", lob: "MOTOR", productCode: "P1" },
  { recordId: "B", premium: -10, bankId: "BANK_A", branchId: "BR_2", zoneId: "ZONE_1", stateId: "STATE_1", monthKey: "2025-08", fy: "FY26", lob: "MOTOR", productCode: "P2" },
  { recordId: "C", premium: 0, bankId: "BANK_B", branchId: "BR_3", zoneId: "ZONE_2", stateId: "STATE_2", monthKey: "2025-09", fy: "FY26", lob: "HEALTH", productCode: "P1" },
  { recordId: "U", premium: 40, bankId: "BANK_A", branchId: "BR_1", zoneId: "ZONE_1", stateId: "STATE_1", monthKey: "2025-08", fy: "FY26", lob: "MOTOR", productCode: "P1" },
  { recordId: "D", premium: 5, bankId: "BANK_B", branchId: "BR_4", zoneId: "ZONE_2", stateId: "STATE_2", monthKey: "2025-09", fy: "FY26", lob: "HEALTH", productCode: "P3" },
];
const result = (id, employeeId, signedActual, temporalStatus) => ({ canonicalRecordReference: id, employeeId, signedActual, businessDate: "2025-08-31", temporalStatus, attributionStatus: employeeId ? "ATTRIBUTED_SOURCE_RM_ID" : "UNATTRIBUTED", diagnostics: temporalStatus === "UNVERIFIED" ? ["ATTRIBUTION_EMPLOYEE_EFFECTIVITY_UNVERIFIED"] : [] });
const results = [result("A", "EMP_1", 100, "EFFECTIVE"), result("B", "EMP_2", -10, "EFFECTIVE"), result("C", "EMP_1", 0, "EFFECTIVE"), result("U", null, 40, "UNVERIFIED"), result("D", "EMP_3", 5, "NOT_EFFECTIVE")];
const roll = (id, owner, nodes, status, manager = null) => ({ canonicalRecordReference: id, directOwnerId: owner, employeeId: owner, signedActual: results.find((item) => item.canonicalRecordReference === id).signedActual, rollupNodeIds: nodes, hierarchyStatus: status, directManagerId: manager, hierarchyDiagnostics: status === "CHAIN_INCOMPLETE" ? ["CHAIN_INCOMPLETE"] : [] });
const rollups = [roll("A", "EMP_1", ["EMP_1", "MGR_1", "ROOT_1"], "RESOLVED", "MGR_1"), roll("B", "EMP_2", ["EMP_2", "MGR_1", "ROOT_1"], "RESOLVED", "MGR_1"), roll("C", "EMP_1", ["EMP_1", "ROOT_2"], "RESOLVED", "ROOT_2"), roll("U", null, [], "MISSING"), roll("D", "EMP_3", ["EMP_3"], "CHAIN_INCOMPLETE")];
const contexts = new Map([["2025-08-31", { status: "READY", deploymentsByEmployee: new Map([["EMP_1", [{}]], ["EMP_4", [{}]]]) }]]);
const directBank = Analytics.sliceDirectPerformance({ canonicalRecords: records, detachedAttributionResults: results, hierarchyRollupRecords: rollups, dimension: "BANK" });
assert.deepStrictEqual(directBank.rows.map((row) => row.key), ["BANK_A", "BANK_B"]); assert.deepStrictEqual(directBank.rows.map((row) => row.acceptedSignedActual), [130, 5]);
const branch = Analytics.sliceDirectPerformance({ canonicalRecords: records, detachedAttributionResults: results, dimension: "BRANCH" }); assert.strictEqual(branch.rows.find((row) => row.key === "BR_1").unattributedSignedActual, 40);
for (const dimension of ["MONTH", "FY", "ZONE", "STATE", "LOB", "PRODUCT", "EMPLOYEE"]) assert.ok(Analytics.sliceDirectPerformance({ canonicalRecords: records, detachedAttributionResults: results, hierarchyRollupRecords: rollups, dimension }).rows.length > 0, dimension);
const scopedProduct = Analytics.sliceDirectPerformance({ canonicalRecords: records, detachedAttributionResults: results, hierarchyRollupRecords: rollups, parentSelection: { dimension: "BRANCH", key: "BR_1" }, dimension: "PRODUCT" });
assert.deepStrictEqual(scopedProduct.rows.map((row) => [row.key, row.acceptedSignedActual]), [["P1", 140]]); assert.strictEqual(scopedProduct.reconciliation.underlyingSignedActual, 140);
const scopedBank = Analytics.sliceDirectPerformance({ canonicalRecords: records, detachedAttributionResults: results, parentSelection: { dimension: "BANK", key: "BANK_A" }, dimension: "BRANCH" }); assert.deepStrictEqual(scopedBank.rows.map((row) => row.key), ["BR_1", "BR_2"]);
const teams = Analytics.sliceTeamPerformance({ canonicalRecords: records, detachedAttributionResults: results, hierarchyRollupRecords: rollups }); assert.strictEqual(teams.nonAdditive, true); assert.strictEqual(teams.rows.find((row) => row.managerEmployeeId === "MGR_1").teamSignedActual, 90); assert.strictEqual(teams.rows.find((row) => row.managerEmployeeId === "ROOT_1").teamSignedActual, 90);
const diagnostics = Analytics.buildDiagnostics({ canonicalRecords: records, detachedAttributionResults: results, hierarchyRollupRecords: rollups, workforceDeploymentContextsByBusinessDate: contexts });
assert.deepStrictEqual([diagnostics.reconciliation.attributedRecordCount, diagnostics.reconciliation.unattributedRecordCount, diagnostics.reconciliation.attributedSignedActual, diagnostics.reconciliation.unattributedSignedActual], [4, 1, 95, 40]); assert.strictEqual(diagnostics.attribution.attributedRecordCoveragePercent, 80); assert.strictEqual(diagnostics.temporalStatusCounts.UNVERIFIED, 1); assert.strictEqual(diagnostics.temporalStatusCounts.NOT_EFFECTIVE, 1); assert.strictEqual(diagnostics.hierarchyStatusCounts.CHAIN_INCOMPLETE, 1);
assert.deepStrictEqual([diagnostics.deployment.deployedWithAttributedBusinessCount, diagnostics.deployment.deployedWithoutAttributedBusinessCount, diagnostics.deployment.attributedBusinessWithoutDeploymentCount], [1, 1, 2]);
assert.strictEqual(Analytics.reconcileSlice({ canonicalRecords: records, detachedAttributionResults: results }).status, "RECONCILED");
const corrupt = results.map((item) => item.canonicalRecordReference === "B" ? { ...item, signedActual: 999 } : item); assert.strictEqual(Analytics.reconcileSlice({ canonicalRecords: records, detachedAttributionResults: corrupt }).status, "UNRECONCILED");
const snapshot = JSON.stringify({ records, results, rollups }); assert.deepStrictEqual(directBank, Analytics.sliceDirectPerformance({ canonicalRecords: records, detachedAttributionResults: results, hierarchyRollupRecords: rollups, dimension: "BANK" })); assert.strictEqual(JSON.stringify({ records, results, rollups }), snapshot);
const source = fs.readFileSync(path.join(__dirname, "..", "js/analytics/workforcePerformance.js"), "utf8"); for (const forbidden of ["Repository", "IndexedDB", "document.", "querySelector", "fetch("]) assert.ok(!source.includes(forbidden), forbidden);
console.log("Step 5C Workforce Performance slices tests passed: governed scopes, diagnostics, reconciliation, leakage prevention, and purity.");
