/* Sprint 3E: evidence-based legacy assignment isolation; no projection is authorized. */
"use strict";
const assert = require("assert"); const path = require("path"); global.window = global;
const load = (file) => require(path.join(__dirname, "..", file)); ["js/data/schema.js", "js/data/datasetRegistry.js", "js/masters/branchMaster.js", "js/masters/employeeMaster.js", "js/masters/branchAssignmentMaster.js", "js/masters/workforceDeployment.js", "js/enrichment/assignmentResolver.js", "js/enrichment/liveAssignmentAuthority.js"].forEach(load);
const legacyEmployees = [{ employeeId: "RM1", employeeName: "RM One", role: "RM", active: true }, { employeeId: "CSM1", employeeName: "CSM One", role: "CSM", active: true }]; const legacyRecords = [{ branchId: "BANK_A:001", bankId: "BANK_A", branchCode: "001", rmId: "RM1", active: true }];
const legacyMaps = BancaTrackerAssignmentResolver.buildLookupMaps(legacyRecords); assert.strictEqual(BancaTrackerAssignmentResolver.resolveAssignment("BANK_A:001", legacyMaps).rmId, "RM1", "Legacy resolver behavior remains unchanged.");
(async function () {
  const nativeIsolationRepository = { getActiveMasterRecords: async (type) => type === "BRANCH_ASSIGNMENT" ? [] : legacyEmployees };
  const nativeContext = await BancaTrackerLiveAssignmentAuthority.loadContext(nativeIsolationRepository); assert.strictEqual(nativeContext.assignmentMaps, null, "Native context is intentionally isolated from RM maps."); const nativeResult = BancaTrackerLiveAssignmentAuthority.applyRecord({ branchId: "BANK_A:001", sourceRmId: "SOURCE1" }, nativeContext); assert.strictEqual(nativeResult.assignmentResolutionStatus, "MASTER_ABSENT"); assert.strictEqual(nativeResult.assignedRmId, null);
  const legacyRepository = { getActiveMasterRecords: async (type) => type === "BRANCH_ASSIGNMENT" ? legacyRecords : legacyEmployees }; const legacyContext = await BancaTrackerLiveAssignmentAuthority.loadContext(legacyRepository); assert.strictEqual(BancaTrackerLiveAssignmentAuthority.applyRecord({ branchId: "BANK_A:001" }, legacyContext).assignedRmId, "RM1");
  const nativeRecord = BancaTrackerWorkforceDeployment.normalizeRecord({ "EMPLOYEE ID": "EXEC1", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "PRIMARY", "VALID FROM": "2025-01-01" }, "DEPLOYMENT:3E", 2); assert.strictEqual("rmId" in nativeRecord, false); assert.strictEqual("premiumOwner" in nativeRecord, false); assert.strictEqual(BancaTrackerWorkforceDeployment.normalizeRecord({ "EMPLOYEE ID": "EXEC1", "BANK ID": "BANK_A", "BRANCH CODE": "001", "DEPLOYMENT TYPE": "SUPPORT", "VALID FROM": "2025-01-01" }, "DEPLOYMENT:3E", 3).deploymentType, "SUPPORT"); assert.strictEqual(BancaTrackerSchema.DATABASE.VERSION, 2);
  console.log("Sprint 3E legacy compatibility tests passed: native isolation, unchanged legacy RM behavior, no role/designation projection, and no attribution.");
})().catch((error) => { console.error(error); process.exit(1); });
