/* Sprint 3C: Workforce Deployment v2 import, lifecycle, and contract isolation. */
"use strict";
const assert = require("assert"); const fs = require("fs"); const path = require("path"); global.window = global;
const load = (file) => require(path.join(__dirname, "..", file));
["js/csvProcessor.js", "js/data/schema.js", "js/data/datasetRegistry.js", "js/masters/branchMaster.js", "js/masters/employeeMaster.js", "js/masters/branchAssignmentMaster.js", "js/masters/workforceDeployment.js"].forEach(load);
const Contract = BancaTrackerDatasetRegistry.WORKFORCE_DEPLOYMENT_DATA_CONTRACT; const validCsv = fs.readFileSync(path.join(__dirname, "fixtures", "workforce-deployment-v2", "valid-many-to-many.csv"), "utf8");
const employee = (employeeId, overrides = {}) => ({ employeeId, employeeName: employeeId, designation: "Executive", employmentStatus: "ACTIVE", dateOfJoining: "2020-01-01", exitDate: null, active: true, ...overrides }); const branch = (branchCode) => ({ branchId: `BANK_A:${branchCode}`, bankId: "BANK_A", branchCode, active: true, validFrom: null, validTo: null });
const employees = [employee("RM001"), employee("USM001"), employee("EXEC001")]; const branches = [branch("001"), branch("002")]; const legacyEmployees = [employee("L_NH", { role: "NATIONAL_HEAD" }), employee("L_ZSM", { role: "ZSM" }), employee("L_ASM", { role: "ASM" }), employee("L_CSM", { role: "CSM" }), employee("L_RM", { role: "RM" })];
class MemoryRepository {
  constructor() { this.datasets = new Map(); this.records = new Map(); this.active = new Map(); this.versions = new Map(); this.stageCalls = 0; }
  async getActiveEmployeeMasterContext() { return { status: "READY", records: employees, diagnostics: [] }; }
  async getActiveMasterRecords(type) { if (type === "BRANCH_MASTER") return branches; if (type === "EMPLOYEE_MASTER") return legacyEmployees; return this.records.get(this.active.get(type)) || []; }
  async stageDataset(metadata) { this.stageCalls += 1; const version = (this.versions.get(metadata.datasetType) || 0) + 1; this.versions.set(metadata.datasetType, version); const dataset = { ...metadata, datasetId: `${metadata.datasetType}:${version}`, datasetVersion: version, status: "STAGED" }; this.datasets.set(dataset.datasetId, dataset); return dataset; }
  async saveStagedMasterRecords(datasetId, records) { this.records.set(datasetId, records); }
  async activateDataset(datasetId) { const dataset = this.datasets.get(datasetId); const previousDatasetId = this.active.get(dataset.datasetType) || null; if (previousDatasetId) this.datasets.get(previousDatasetId).status = "SUPERSEDED"; dataset.status = "ACTIVE"; this.active.set(dataset.datasetType, datasetId); return { success: true, datasetId, previousDatasetId }; }
  async markDatasetFailed(datasetId) { this.datasets.get(datasetId).status = "FAILED"; }
}
let dbState = { activeId: null, datasets: new Map(), records: [] };
global.BancaTrackerIndexedDb = { async get(store, key) { if (store === BancaTrackerSchema.STORES.APP_METADATA) return key === "activeDataset:BRANCH_ASSIGNMENT" && dbState.activeId ? { key, value: dbState.activeId } : null; if (store === BancaTrackerSchema.STORES.DATASETS) return dbState.datasets.get(key) || null; return null; }, async getAllByIndex(store, index, value) { return store === BancaTrackerSchema.STORES.BRANCH_ASSIGNMENTS && index === "datasetId" && value === dbState.activeId ? dbState.records : []; } };
load("js/data/repository.js"); load("js/masterDataImport.js");
const Importer = BancaTrackerMasterDataImport; const preview = (repository, text) => Importer.prepareImport("BRANCH_ASSIGNMENT", Importer.parseText(text), { repository, fileName: "deployment.csv" });

(async function () {
  assert.strictEqual(BancaTrackerSchema.DATABASE.VERSION, 2, "Workforce Deployment v2 needs no IndexedDB version change.");
  const repository = new MemoryRepository(); const native = await preview(repository, validCsv); assert.strictEqual(native.valid, true); assert.strictEqual(native.deploymentProfile.sourceProfile, Contract.PROFILES.WORKFORCE_DEPLOYMENT_V2); assert.strictEqual(native.contractMetadata.dataContract.version, 2);
  const commit = await Importer.commitImport(native, { repository }); assert.strictEqual(commit.dataset.datasetVersion, 1); assert.strictEqual(commit.dataset.metadata.dataContract.sourceProfile, Contract.PROFILES.WORKFORCE_DEPLOYMENT_V2); assert.deepStrictEqual(Object.keys(commit.records[0]).sort(), ["recordId", "datasetId", "employeeId", "bankId", "branchCode", "branchId", "deploymentType", "validFrom", "validTo", "sourceRowNumber"].sort()); assert.ok(commit.records.every((record) => !("rmId" in record) && !("premium" in record) && !("reportingChain" in record)));
  const invalid = await preview(repository, "EMPLOYEE ID,BANK ID,BRANCH CODE,DEPLOYMENT TYPE,VALID FROM\nUNKNOWN,BANK_A,001,PRIMARY,2025-01-01"); const activeBeforeInvalid = repository.active.get("BRANCH_ASSIGNMENT"); assert.strictEqual(invalid.valid, false); await assert.rejects(() => Importer.commitImport(invalid, { repository }), /valid preview/); assert.strictEqual(repository.active.get("BRANCH_ASSIGNMENT"), activeBeforeInvalid);
  const mixed = await preview(repository, "EMPLOYEE ID,RM ID,BANK ID,BRANCH CODE,DEPLOYMENT TYPE,VALID FROM\nRM001,L_RM,BANK_A,001,PRIMARY,2025-01-01"); assert.strictEqual(mixed.valid, false); assert.ok(mixed.findings.some((finding) => finding.code === "WORKFORCE_DEPLOYMENT_MIXED_CONTRACT_PROHIBITED")); assert.strictEqual(repository.active.get("BRANCH_ASSIGNMENT"), activeBeforeInvalid);
  const legacy = await preview(repository, "BANK ID,BRANCH CODE,RM ID,ACTIVE\nBANK_A,001,L_RM,TRUE"); assert.strictEqual(legacy.valid, true); assert.strictEqual(legacy.deploymentProfile.sourceProfile, Contract.PROFILES.LEGACY_V1); const legacyCommit = await Importer.commitImport(legacy, { repository }); assert.strictEqual(legacyCommit.dataset.metadata.dataContract.version, 1);
  const unavailableEmployee = new MemoryRepository(); unavailableEmployee.getActiveEmployeeMasterContext = async () => ({ status: "ABSENT", records: [], diagnostics: [] }); const employeeBlocked = await preview(unavailableEmployee, validCsv); assert.ok(employeeBlocked.findings.some((finding) => finding.code === "DEPLOYMENT_V2_EMPLOYEE_MASTER_UNAVAILABLE"));
  const unavailableBranch = new MemoryRepository(); unavailableBranch.getActiveMasterRecords = async (type) => type === "BRANCH_MASTER" ? [] : []; const branchBlocked = await preview(unavailableBranch, validCsv); assert.ok(branchBlocked.findings.some((finding) => finding.code === "DEPLOYMENT_V2_BRANCH_MASTER_UNAVAILABLE"));
  const legacyEmployeeContext = new MemoryRepository(); legacyEmployeeContext.getActiveEmployeeMasterContext = async () => ({ status: "LEGACY_COMPATIBILITY", records: employees, diagnostics: [] }); assert.strictEqual((await preview(legacyEmployeeContext, validCsv)).valid, true, "Supported legacy-compatible Employee context is usable.");
  const nativeDataset = { ...commit.dataset, datasetId: "BRANCH_ASSIGNMENT:99", status: "ACTIVE" }; dbState = { activeId: nativeDataset.datasetId, datasets: new Map([[nativeDataset.datasetId, nativeDataset]]), records: commit.records.map((record) => ({ ...record, datasetId: nativeDataset.datasetId, recordId: record.recordId.replace(commit.dataset.datasetId, nativeDataset.datasetId) })) };
  const nativeContext = await BancaTrackerRepository.getActiveWorkforceDeploymentContext(); assert.strictEqual(nativeContext.status, "READY"); assert.strictEqual(nativeContext.contract.sourceProfile, Contract.PROFILES.WORKFORCE_DEPLOYMENT_V2); assert.strictEqual(nativeContext.records[0].deploymentType, "PRIMARY"); assert.deepStrictEqual(await BancaTrackerRepository.getActiveMasterRecords("BRANCH_ASSIGNMENT"), [], "Native canonical records cannot leak into legacy RM resolver reads.");
  const metadataLess = { datasetId: "BRANCH_ASSIGNMENT:LEGACY", status: "ACTIVE", metadata: null }; dbState.activeId = metadataLess.datasetId; dbState.datasets.set(metadataLess.datasetId, metadataLess); dbState.records = [{ datasetId: metadataLess.datasetId, recordId: "legacy", branchId: "BANK_A:001", rmId: "L_RM", active: true }]; const legacyContext = await BancaTrackerRepository.getActiveWorkforceDeploymentContext(); assert.strictEqual(legacyContext.status, "LEGACY_COMPATIBILITY"); assert.strictEqual(legacyContext.contract.sourceProfile, Contract.PROFILES.LEGACY_V1_ASSUMED); assert.strictEqual((await BancaTrackerRepository.getActiveMasterRecords("BRANCH_ASSIGNMENT")).length, 1);
  const unsupported = { datasetId: "BRANCH_ASSIGNMENT:UNSUPPORTED", metadata: { dataContract: { name: Contract.NAME, version: 9, sourceProfile: "WORKFORCE_DEPLOYMENT_V9" } } }; dbState.activeId = unsupported.datasetId; dbState.datasets.set(unsupported.datasetId, unsupported); assert.strictEqual((await BancaTrackerRepository.getActiveWorkforceDeploymentContext()).status, "UNSUPPORTED_CONTRACT"); dbState.activeId = null; assert.strictEqual((await BancaTrackerRepository.getActiveWorkforceDeploymentContext()).status, "ABSENT");
  console.log("Sprint 3C Workforce Deployment persistence tests passed: profile routing, lifecycle, metadata, dual-read contexts, replacement safety, and native isolation.");
})().catch((error) => { console.error(error); process.exit(1); });
