/* v8.1 Step 8.1E acceptance fixes: unknown banks, bounded rendering, active pages, and deterministic hierarchy. */
const assert = require("assert"); const path = require("path");
class Element { constructor() { this.value = ""; this.innerHTML = ""; this.textContent = ""; this.style = {}; this.classList = { toggle() {} }; } addEventListener() {} add() {} }
const elements = {}; global.window = global; global.document = { getElementById(id) { return elements[id] || (elements[id] = new Element()); } }; global.Option = class {}; global.sessionStorage = { getItem() { return null; }, setItem() {} }; global.performance = require("perf_hooks").performance;
const load = (file) => require(path.join(__dirname, "..", file)); ["js/config.js", "js/csvProcessor.js", "js/utilities.js", "js/analytics.js", "js/dataQuality.js", "js/productivity.js", "js/core.js", "js/performance.js", "app.js", "js/activation.js", "js/scorecard.js", "js/target.js"].forEach(load);
const H = "USGI NET PREMIUM,Month,INTERMEDIARY,BA NAME,Ba Code,LINE OF BUSINESS,BRANCH NAME,Zone,STATE,SUM IMD CODE,Business Type,PRODUCT NAME,PRODUCT CODE,Day";

const counts = { mis: 0, activation: 0, scorecard: 0, target: 0, productivity: 0, quality: 0 };
const wrap = (name, key) => { const original = global[name]; global[name] = function (...args) { counts[key] += 1; return original(...args); }; };
wrap("renderPerformance", "mis"); wrap("refreshActivation", "activation"); wrap("refreshScorecard", "scorecard"); wrap("refreshTarget", "target"); wrap("renderProductivity", "productivity"); wrap("renderDataQuality", "quality");

const initial = [
  "10000,Apr-26,INDIAN BANK,RM A,A1,Motor,IB A,South,Tamil Nadu,I1,Fresh,Motor,P1,1",
  "20000,Jun-26,UNLISTED BANK,RM U,U1,Motor,Unknown Near,West,Karnataka,UI1,Fresh,Motor,P1,1"
];
BancaTrackerCore.loadCsvText([H, ...initial].join("\n"));
assert.strictEqual(counts.mis, 1); assert.strictEqual(counts.activation, 0); assert.strictEqual(counts.scorecard, 0); assert.strictEqual(counts.target, 0); assert.strictEqual(counts.productivity, 0); assert.strictEqual(counts.quality, 0);
BancaTrackerApp.showPage("activationPage"); assert.strictEqual(counts.activation, 1); assert.ok(elements.activationScope.textContent.includes("Jun-26"));
BancaTrackerCore.state.filters.month = "Apr-26"; BancaTrackerCore.refresh(); assert.strictEqual(counts.activation, 2); assert.strictEqual(counts.mis, 1);
BancaTrackerCore.state.filters.bank = "INDIAN BANK"; BancaTrackerCore.refresh(); assert.strictEqual(counts.activation, 3); BancaTrackerApp.showPage("productivityPage"); assert.strictEqual(counts.productivity, 1); assert.ok(elements.productivityScope.textContent.includes("Apr-26"));
const targetBeforeImport = counts.target;
BancaTrackerCore.loadCsvText([H, ...initial].join("\n")); assert.strictEqual(counts.productivity, 2); assert.strictEqual(counts.target, targetBeforeImport); BancaTrackerApp.showPage("targetPage"); assert.strictEqual(counts.target, targetBeforeImport + 1); assert.ok(elements.targetKpis.innerHTML.includes("YTD Actual"));

BancaTrackerCore.state.filters.month = "ALL"; BancaTrackerCore.state.filters.bank = "ALL"; BancaTrackerCore.refresh(); BancaTrackerApp.showPage("scorecardPage");
const metrics = BancaTrackerScorecard.buildPartnerMetrics(BancaTrackerCore.state.derived, BancaTrackerCore.state.productivity, BancaTrackerCore.state.dataQuality, "ALL");
const unknown = metrics.find((item) => item.bank === "UNLISTED BANK"); assert.ok(unknown); assert.strictEqual(unknown.branchUniverse, null); assert.strictEqual(unknown.priority, "UNCONFIGURED"); assert.strictEqual(unknown.premium, 20000);
const contributionTotal = metrics.reduce((sum, item) => sum + item.contributionPercent, 0); assert.ok(Math.abs(contributionTotal - 100) < 1e-10); assert.ok(elements.partnerScorecard.innerHTML.includes("UNLISTED BANK")); assert.ok(elements.partnerScorecard.innerHTML.includes("Not configured")); assert.ok(elements.partnerScorecard.innerHTML.includes("N/A")); assert.ok(elements.partnerScorecard.innerHTML.includes("UNCONFIGURED"));
BancaTrackerScorecard.selectBank("UNLISTED BANK"); assert.ok(elements.managementDetail.innerHTML.includes("UNLISTED BANK Management Detail")); assert.ok(elements.managementDetail.innerHTML.includes("Unknown Near"));

const qualityRows = [];
for (let index = 0; index < 101; index += 1) { const base = { premium: 1, month: "Apr-26", bank: "INDIAN BANK", lob: "Motor", branch: `Conflict ${index}`, state: "Tamil Nadu", imd: "I", businessType: "Fresh", productName: "Motor", productCode: "P", day: "1", baCode: `B${index}` }; qualityRows.push({ ...base, zone: "North", rm: "RM A" }, { ...base, premium: 2, zone: "West", rm: "RM B" }); }
for (let index = 0; index < 55; index += 1) { const row = { premium: 10, month: "Apr-26", bank: "INDIAN BANK", rm: `D${index}`, baCode: `D${index}`, lob: "Motor", branch: `Duplicate ${index}`, zone: "North", state: "Tamil Nadu", imd: `DI${index}`, businessType: "Fresh", productName: "Motor", productCode: "P", day: "1" }; qualityRows.push({ ...row }, { ...row }); }
const audit = BancaTrackerDataQuality.build(qualityRows, BancaTrackerConfig, { acceptedRows: qualityRows.length, rejectedRows: 0, warningRows: 0 }); const hierarchyCount = audit.hierarchyConflicts.length; const identityCount = audit.identityConflicts.length; const duplicateCount = audit.duplicateSignals;
BancaTrackerDataQuality.render(audit); assert.strictEqual(audit.hierarchyConflicts.length, hierarchyCount); assert.strictEqual(audit.identityConflicts.length, identityCount); assert.strictEqual(audit.duplicateSignals, duplicateCount); assert.ok(hierarchyCount > 100 && identityCount > 100 && audit.duplicateGroupCount > 50); assert.ok(elements.hierarchyConflicts.innerHTML.includes("Showing 100 of")); assert.ok(elements.identityConflicts.innerHTML.includes("Showing 100 of")); assert.ok(elements.duplicateSignals.innerHTML.includes("Showing 50 of"));

function hierarchyCsv(reverse) { const pair = ["10000,Jun-26,INDIAN BANK,RM A,A1,Motor,Shared Branch,North,Tamil Nadu,I1,Fresh,Motor,P1,1", "10000,Jun-26,INDIAN BANK,RM A,A1,Motor,Shared Branch,West,Karnataka,I1,Fresh,Motor,P1,1"]; if (reverse) pair.reverse(); return [H, ...pair].join("\n"); }
BancaTrackerCore.loadCsvText(hierarchyCsv(false)); let derived = BancaTrackerCore.state.derived; assert.ok(derived.zones["Multiple mappings"]); assert.ok(derived.states["Multiple mappings"]); assert.strictEqual(derived.branches[0].zone, "Multiple mappings"); assert.strictEqual(derived.branches[0].state, "Multiple mappings"); assert.ok(BancaTrackerCore.state.dataQuality.hierarchyConflicts.length >= 2); const first = JSON.stringify({ zones: derived.zones, states: derived.states, zone: derived.branches[0].zone, state: derived.branches[0].state });
BancaTrackerCore.loadCsvText(hierarchyCsv(true)); derived = BancaTrackerCore.state.derived; const second = JSON.stringify({ zones: derived.zones, states: derived.states, zone: derived.branches[0].zone, state: derived.branches[0].state }); assert.strictEqual(second, first); BancaTrackerApp.showPage("activationPage"); assert.ok(elements.zoneActivation.innerHTML.includes("Multiple mappings")); assert.ok(elements.stateActivation.innerHTML.includes("Multiple mappings"));

const odd = "1000,Odd-Month,INDIAN BANK,RM A,A1,Motor,Odd Branch,North,Tamil Nadu,I1,Fresh,Motor,P1,1"; BancaTrackerCore.loadCsvText([H, odd].join("\n")); BancaTrackerCore.state.filters.month = "Odd-Month"; BancaTrackerCore.refresh(); const oddContext = BancaTrackerCore.getPerformanceContext(); assert.strictEqual(oddContext.currentPeriodMonth, "Odd-Month"); assert.strictEqual(oddContext.currentPeriodIsUnconfigured, true); assert.strictEqual(oddContext.ytdData.length, 0); assert.strictEqual(oddContext.elapsedMonths, null); BancaTrackerApp.showPage("misPage"); assert.ok(elements.performanceScope.textContent.includes("unconfigured"));
const unsafeBank = "20000,Jun-26,<script>alert(1)</script>,RM X,X1,Motor,Unsafe Bank Branch,North,Tamil Nadu,XI,Fresh,Motor,P1,1"; BancaTrackerCore.loadCsvText([H, unsafeBank].join("\n")); BancaTrackerApp.showPage("scorecardPage"); assert.ok(!elements.partnerScorecard.innerHTML.includes("<SCRIPT>ALERT(1)</SCRIPT>")); assert.ok(elements.partnerScorecard.innerHTML.includes("&lt;SCRIPT&gt;")); BancaTrackerScorecard.selectBank("<SCRIPT>ALERT(1)</SCRIPT>"); assert.ok(!elements.managementDetail.innerHTML.includes("<SCRIPT>ALERT(1)</SCRIPT>")); assert.ok(elements.managementDetail.innerHTML.includes("&lt;SCRIPT&gt;"));
console.log("v8.1 Step 8.1E tests passed: unknown banks, reconciliation, bounded diagnostics, active pages, deterministic hierarchy, imports, filters, and unconfigured months.");
