/* Sprint 3F: browser-facing Workforce Deployment v2 acceptance lifecycle. */
"use strict";
const assert = require("assert"); const fs = require("fs"); const path = require("path"); global.window = global;
const load = (file) => require(path.join(__dirname, "..", file)); const fixture = (name) => fs.readFileSync(path.join(__dirname, "fixtures", "workforce-deployment-v2", name), "utf8");
["js/csvProcessor.js", "js/data/schema.js", "js/data/datasetRegistry.js", "js/masters/branchMaster.js", "js/masters/employeeMaster.js", "js/masters/branchAssignmentMaster.js", "js/masters/workforceDeployment.js", "js/enrichment/assignmentResolver.js", "js/enrichment/liveAssignmentAuthority.js", "js/enrichment/workforceDeploymentResolver.js"].forEach(load);
const Contract = BancaTrackerDatasetRegistry.WORKFORCE_DEPLOYMENT_DATA_CONTRACT; const employee = (id, role = null) => ({ employeeId: id, employeeName: id, designation: role === "RM" ? "Relationship Manager" : "Executive", role, employmentStatus: "ACTIVE", dateOfJoining: "2024-01-01", exitDate: null, active: true }); const employees = [employee("EMP001", "RM"), employee("EMP002"), employee("EMP003"), employee("EMP004"), employee("LEGACY_RM", "RM")]; const branches = ["001", "002", "003"].map((branchCode) => ({ branchId: `BANK_A:${branchCode}`, bankId: "BANK_A", branchCode, active: true, validFrom: null, validTo: null }));
class MemoryRepository { constructor() { this.datasets = new Map(); this.records = new Map(); this.active = new Map(); this.versions = new Map(); } async getActiveEmployeeMasterContext() { return { status: "READY", records: employees, diagnostics: [] }; } async getActiveMasterRecords(type) { if (type === "BRANCH_MASTER") return branches; if (type === "EMPLOYEE_MASTER") return employees; return this.records.get(this.active.get(type)) || []; } async stageDataset(metadata) { const version = (this.versions.get(metadata.datasetType) || 0) + 1; this.versions.set(metadata.datasetType, version); const dataset = { ...metadata, datasetId: `${metadata.datasetType}:${version}`, datasetVersion: version, status: "STAGED" }; this.datasets.set(dataset.datasetId, dataset); return dataset; } async saveStagedMasterRecords(id, records) { this.records.set(id, records); } async activateDataset(id) { const dataset = this.datasets.get(id); const previousDatasetId = this.active.get(dataset.datasetType) || null; if (previousDatasetId) this.datasets.get(previousDatasetId).status = "SUPERSEDED"; dataset.status = "ACTIVE"; this.active.set(dataset.datasetType, id); return { success: true, datasetId: id, previousDatasetId }; } async markDatasetFailed(id) { this.datasets.get(id).status = "FAILED"; } }
let dbState = { activeId: null, datasets: new Map(), records: [] }; global.BancaTrackerIndexedDb = { async get(store, key) { if (store === BancaTrackerSchema.STORES.APP_METADATA) return key === "activeDataset:BRANCH_ASSIGNMENT" && dbState.activeId ? { key, value: dbState.activeId } : null; if (store === BancaTrackerSchema.STORES.DATASETS) return dbState.datasets.get(key) || null; return null; }, async getAllByIndex(store, index, value) { return store === BancaTrackerSchema.STORES.BRANCH_ASSIGNMENTS && index === "datasetId" && value === dbState.activeId ? dbState.records : []; } };
load("js/data/repository.js"); load("js/masterDataImport.js"); const Importer = BancaTrackerMasterDataImport; const preview = (repository, text, name) => Importer.prepareImport("BRANCH_ASSIGNMENT", Importer.parseText(text), { repository, fileName: name });
(async function () {
  assert.strictEqual(BancaTrackerSchema.DATABASE.VERSION, 2); const repository = new MemoryRepository(); const valid = await preview(repository, fixture("acceptance-valid-native-v2.csv"), "acceptance-valid-native-v2.csv"); assert.strictEqual(valid.valid, true); assert.strictEqual(valid.deploymentProfile.sourceProfile, Contract.PROFILES.WORKFORCE_DEPLOYMENT_V2); const commit = await Importer.commitImport(valid, { repository }); assert.strictEqual(commit.dataset.status, "ACTIVE"); assert.strictEqual(commit.dataset.metadata.dataContract.sourceProfile, Contract.PROFILES.WORKFORCE_DEPLOYMENT_V2);
  const nativeDataset = { ...commit.dataset, datasetId: "BRANCH_ASSIGNMENT:ACCEPTANCE", status: "ACTIVE" }; dbState = { activeId: nativeDataset.datasetId, datasets: new Map([[nativeDataset.datasetId, nativeDataset]]), records: commit.records.map((record) => ({ ...record, datasetId: nativeDataset.datasetId, recordId: record.recordId.replace(commit.dataset.datasetId, nativeDataset.datasetId) })) };
  const activeContext = await BancaTrackerRepository.getActiveWorkforceDeploymentContext(); assert.strictEqual(activeContext.status, "READY"); assert.strictEqual(activeContext.records.length, 6); assert.ok(activeContext.records.every((record) => !("rmId" in record) && !("premium" in record) && !("manager" in record))); const august = await BancaTrackerRepository.getActiveWorkforceDeploymentResolutionContext("2025-08-31"); const october = await BancaTrackerRepository.getActiveWorkforceDeploymentResolutionContext("2025-10-31"); assert.strictEqual(august.status, "READY"); assert.deepStrictEqual(BancaTrackerWorkforceDeploymentResolver.resolveEmployee("EMP001", august).deployments.map((record) => [record.branchId, record.deploymentType]), [["BANK_A:001", "PRIMARY"], ["BANK_A:003", "SUPPORT"]]); const branch = BancaTrackerWorkforceDeploymentResolver.resolveBranch("BANK_A:001", august); assert.strictEqual(branch.primary.employeeId, "EMP001"); assert.deepStrictEqual(branch.support.map((record) => record.employeeId), ["EMP002", "EMP003"]); assert.strictEqual(BancaTrackerWorkforceDeploymentResolver.resolveBranch("BANK_A:003", august).primary, null); assert.strictEqual(BancaTrackerWorkforceDeploymentResolver.resolveEmployee("EMP001", october).deployments.find((record) => record.deploymentType === "PRIMARY").branchId, "BANK_A:002"); assert.strictEqual(BancaTrackerWorkforceDeploymentResolver.resolveBranch("BANK_A:001", await BancaTrackerRepository.getActiveWorkforceDeploymentResolutionContext("2025-01-01")).primary.employeeId, "EMP001"); assert.strictEqual(BancaTrackerWorkforceDeploymentResolver.resolveBranch("BANK_A:001", await BancaTrackerRepository.getActiveWorkforceDeploymentResolutionContext("2025-09-30")).primary.employeeId, "EMP001");
  assert.deepStrictEqual(await BancaTrackerRepository.getActiveMasterRecords("BRANCH_ASSIGNMENT"), []); const isolated = await BancaTrackerLiveAssignmentAuthority.loadContext(BancaTrackerRepository); assert.strictEqual(isolated.assignmentMaps, null); assert.strictEqual(BancaTrackerLiveAssignmentAuthority.applyRecord({ branchId: "BANK_A:001" }, isolated).assignedRmId, null);
  const activeBeforeInvalid = repository.active.get("BRANCH_ASSIGNMENT"); const invalid = await preview(repository, fixture("acceptance-invalid-native-v2.csv"), "acceptance-invalid-native-v2.csv"); assert.strictEqual(invalid.valid, false); assert.ok(invalid.findings.some((finding) => finding.code === "DEPLOYMENT_V2_BRANCH_PRIMARY_OVERLAP")); await assert.rejects(() => Importer.commitImport(invalid, { repository }), /valid preview/); assert.strictEqual(repository.active.get("BRANCH_ASSIGNMENT"), activeBeforeInvalid);
  const legacy = await preview(repository, fixture("legacy-branch-assignment.csv"), "legacy-branch-assignment.csv"); assert.strictEqual(legacy.valid, true); const legacyCommit = await Importer.commitImport(legacy, { repository }); assert.strictEqual(legacyCommit.dataset.metadata.dataContract.sourceProfile, Contract.PROFILES.LEGACY_V1); assert.strictEqual(BancaTrackerAssignmentResolver.resolveAssignment("BANK_A:001", BancaTrackerAssignmentResolver.buildLookupMaps(legacyCommit.records)).rmId, "LEGACY_RM");
  console.log("Sprint 3F Workforce Deployment browser acceptance tests passed: fixtures, lifecycle, native context, temporal resolution, isolation, replacement safety, and legacy compatibility.");
})().catch((error) => { console.error(error); process.exit(1); });
