/* Step 5B: pure workforce performance composition. */
"use strict";
const assert = require("assert"); const fs = require("fs"); const path = require("path"); const vm = require("vm");
global.window = global;
vm.runInThisContext(fs.readFileSync(path.join(__dirname, "..", "js/analytics/workforcePerformance.js"), "utf8"), { filename: "workforcePerformance.js" });
const Analytics = BancaTrackerWorkforcePerformance;
const attributed = (reference, employeeId, signedActual, businessDate = "2025-08-31") => ({ canonicalRecordReference: reference, employeeId, signedActual, businessDate, attributionStatus: employeeId ? "ATTRIBUTED_SOURCE_RM_ID" : "UNATTRIBUTED", temporalStatus: employeeId ? "EFFECTIVE" : "UNRESOLVED", diagnostics: [] });
const results = [attributed("A", "EMP1", 100), attributed("B", "EMP1", -10), attributed("C", "EMP2", 0), attributed("D", "MGR1", 20), attributed("H", "EMP1", 5, "2025-10-31"), attributed("P", "EMP3", 7), attributed("U", null, 40)];
const rollup = [
  { ...results[0], directOwnerId: "EMP1", rollupNodeIds: ["EMP1", "MGR1", "ROOT_A"], hierarchyStatus: "RESOLVED", rootEmployeeId: "ROOT_A", hierarchyDiagnostics: [] },
  { ...results[1], directOwnerId: "EMP1", rollupNodeIds: ["EMP1", "MGR1", "ROOT_A"], hierarchyStatus: "RESOLVED", rootEmployeeId: "ROOT_A", hierarchyDiagnostics: [] },
  { ...results[2], directOwnerId: "EMP2", rollupNodeIds: ["EMP2", "ROOT_B"], hierarchyStatus: "RESOLVED", rootEmployeeId: "ROOT_B", hierarchyDiagnostics: [] },
  { ...results[3], directOwnerId: "MGR1", rollupNodeIds: ["MGR1", "ROOT_A"], hierarchyStatus: "RESOLVED", rootEmployeeId: "ROOT_A", hierarchyDiagnostics: [] },
  { ...results[4], directOwnerId: "EMP1", rollupNodeIds: ["EMP1", "MGR2", "ROOT_A"], hierarchyStatus: "RESOLVED", rootEmployeeId: "ROOT_A", hierarchyDiagnostics: [] },
  { ...results[5], directOwnerId: "EMP3", rollupNodeIds: ["EMP3"], hierarchyStatus: "CHAIN_INCOMPLETE", rootEmployeeId: null, hierarchyDiagnostics: ["CHAIN_INCOMPLETE"] },
  { ...results[6], directOwnerId: null, rollupNodeIds: [], hierarchyStatus: "UNATTRIBUTED", rootEmployeeId: null, hierarchyDiagnostics: [] },
];
const contexts = new Map([["2025-08-31", { status: "READY", deploymentsByEmployee: new Map([["EMP1", [{ branchId: "B1" }]], ["EMP3", [{ branchId: "B2" }]], ["EMP4", [{ branchId: "B3" }]]]), diagnostics: [] }], ["2025-10-31", { status: "READY", deploymentsByEmployee: new Map([["EMP1", [{ branchId: "B1" }]]]), diagnostics: [] }]]);
const reconciliationResult = { status: "RECONCILED", coverage: { attributedSignedActual: 122, attributedRecords: 6, unattributedSignedActual: 40, unattributedRecords: 1 } };
const employeeRows = Analytics.buildEmployeePerformance(results, reconciliationResult);
assert.deepStrictEqual(employeeRows.map((row) => row.employeeId), ["EMP1", "EMP2", "EMP3", "MGR1"]); assert.strictEqual(employeeRows.find((row) => row.employeeId === "EMP1").directSignedActual, 95); assert.strictEqual(employeeRows.find((row) => row.employeeId === "EMP1").directContributionPercent, 95 / 122 * 100); assert.strictEqual(employeeRows.find((row) => row.employeeId === "EMP2").directSignedActual, 0); assert.strictEqual(employeeRows.some((row) => row.employeeId === null), false);
const teams = Analytics.buildTeamPerformance(rollup); const manager = teams.find((row) => row.managerEmployeeId === "MGR1");
assert.deepStrictEqual([manager.ownDirectAttributedRecordCount, manager.ownDirectSignedActual, manager.descendantAttributedRecordCount, manager.descendantSignedActual, manager.teamSignedActual], [1, 20, 2, 90, 110]); assert.strictEqual(teams.find((row) => row.managerEmployeeId === "ROOT_A").teamSignedActual, 115); assert.strictEqual(teams.find((row) => row.managerEmployeeId === "ROOT_B").teamSignedActual, 0); assert.strictEqual(teams.find((row) => row.managerEmployeeId === "EMP3").teamStatus, "PARTIAL_HIERARCHY");
assert.strictEqual(teams.find((row) => row.managerEmployeeId === "MGR2").teamSignedActual, 5);
const alignment = Analytics.buildDeploymentAlignment(results, contexts, { employeeIds: ["EMP5"], businessDate: "2025-08-31" }); const findAlignment = (employeeId, businessDate) => alignment.find((row) => row.employeeId === employeeId && row.businessDate === businessDate);
assert.strictEqual(findAlignment("EMP1", "2025-08-31").classification, "DEPLOYED_WITH_ATTRIBUTED_BUSINESS"); assert.strictEqual(findAlignment("EMP4", "2025-08-31").classification, "DEPLOYED_WITHOUT_ATTRIBUTED_BUSINESS"); assert.strictEqual(findAlignment("MGR1", "2025-08-31").classification, "ATTRIBUTED_BUSINESS_WITHOUT_DEPLOYMENT"); assert.strictEqual(findAlignment("EMP5", "2025-08-31").classification, "NO_DEPLOYMENT_NO_ATTRIBUTED_BUSINESS"); assert.strictEqual(alignment.some((row) => row.employeeId === "EMP4" && row.directAttributedRecordCount > 0), false);
assert.strictEqual(Analytics.buildDeploymentAlignment([attributed("X", "EMP6", 1, "2025-11-30")], contexts).find((row) => row.employeeId === "EMP6").classification, "DEPLOYMENT_CONTEXT_UNAVAILABLE");
const report = Analytics.summarize({ detachedAttributionResults: results, hierarchyRollupRecords: rollup, workforceDeploymentContextsByBusinessDate: contexts, reconciliationResult, employeeIds: ["EMP5"], businessDate: "2025-08-31" }); assert.strictEqual(report.status, "RECONCILED"); assert.strictEqual(report.metadata.teamMembership, "INCLUSIVE_SELF_AND_DESCENDANTS");
assert.deepStrictEqual([report.coverage.hierarchy.attributedRecordCount, report.coverage.hierarchy.partialRecordCount, report.coverage.deployment.deployedWithAttributedBusinessCount, report.coverage.deployment.attributedBusinessWithoutDeploymentCount], [6, 1, 3, 2]);
assert.strictEqual(Analytics.validateReconciliation({ attributionResults: results, rollupRecords: rollup, employeeRows, deploymentRows: alignment, reconciliationResult }).status, "RECONCILED"); assert.strictEqual(Analytics.validateReconciliation({ attributionResults: results, rollupRecords: rollup, employeeRows: [{ employeeId: "EMP1", directSignedActual: 1 }], deploymentRows: alignment, reconciliationResult }).status, "UNRECONCILED");
const before = JSON.stringify({ results, rollup, contexts: [...contexts.entries()].map(([date, context]) => [date, [...context.deploymentsByEmployee.entries()]]) }); assert.deepStrictEqual(report, Analytics.summarize({ detachedAttributionResults: results, hierarchyRollupRecords: rollup, workforceDeploymentContextsByBusinessDate: contexts, reconciliationResult, employeeIds: ["EMP5"], businessDate: "2025-08-31" })); assert.strictEqual(JSON.stringify({ results, rollup, contexts: [...contexts.entries()].map(([date, context]) => [date, [...context.deploymentsByEmployee.entries()]]) }), before);
const source = fs.readFileSync(path.join(__dirname, "..", "js/analytics/workforcePerformance.js"), "utf8"); for (const forbidden of ["Repository", "IndexedDB", "document.", "querySelector", "fetch("]) assert.ok(!source.includes(forbidden), forbidden);
console.log("Step 5B Workforce Performance tests passed: direct, team, deployment context, reconciliation, determinism, and purity.");
