/*==============================================================
BancaTracker Enterprise
Version : 8.3.0
File    : workforceDeploymentResolver.js
Module  : Enrichment Foundation
Purpose : Resolve active native workforce deployments at an explicit date
==============================================================*/

(function (global) {
  "use strict";
  if (!global.BancaTrackerWorkforceDeployment) throw new Error("BancaTrackerWorkforceDeployment must be loaded before workforceDeploymentResolver.js");
  const Authority = global.BancaTrackerWorkforceDeployment;
  function emptyContext(status, asOfDate, sourceContext, diagnostics) { return Object.freeze({ status, asOfDate: asOfDate || null, sourceContext: sourceContext || null, deploymentCount: 0, effectiveDeploymentCount: 0, employeeCount: 0, branchCount: 0, deploymentsByEmployee: new Map(), deploymentsByBranch: new Map(), primaryByBranch: new Map(), supportByBranch: new Map(), primaryConflictBranchIds: new Set(), coverage: Object.freeze({ totalCanonicalDeployments: 0, effectiveDeployments: 0, employeesRepresented: 0, branchesRepresented: 0, branchesWithPrimary: 0, branchesWithSupport: 0, branchesWithNoPrimary: 0, employeesWithMultipleEffectiveBranches: 0 }), diagnostics: Object.freeze(diagnostics || []) }); }
  function isEffective(record, asOfDate) { return Boolean(record && record.dateValidity && record.dateValidity.validFrom && record.dateValidity.validTo && record.validFrom && record.validFrom <= asOfDate && (!record.validTo || asOfDate <= record.validTo)); }
  function freezeIndex(index) { const result = new Map(); [...index.keys()].sort().forEach((key) => result.set(key, Object.freeze([...index.get(key)].sort((a, b) => a.branchId.localeCompare(b.branchId) || a.employeeId.localeCompare(b.employeeId) || a.deploymentType.localeCompare(b.deploymentType) || a.validFrom.localeCompare(b.validFrom))))); return result; }
  function createContext(workforceDeploymentContext, asOfDate) {
    const parsedDate = Authority.parseDate(asOfDate); if (!parsedDate.value || !parsedDate.valid) return emptyContext("INVALID_AS_OF_DATE", asOfDate, workforceDeploymentContext, ["WORKFORCE_DEPLOYMENT_AS_OF_INVALID"]);
    if (!workforceDeploymentContext || workforceDeploymentContext.status === "ABSENT") return emptyContext("ABSENT", parsedDate.value, workforceDeploymentContext, ["WORKFORCE_DEPLOYMENT_ABSENT"]);
    if (workforceDeploymentContext.status === "LEGACY_COMPATIBILITY") return emptyContext("LEGACY_COMPATIBILITY", parsedDate.value, workforceDeploymentContext, ["WORKFORCE_DEPLOYMENT_LEGACY_NOT_ADAPTED"]);
    if (workforceDeploymentContext.status === "UNSUPPORTED_CONTRACT") return emptyContext("UNSUPPORTED_CONTRACT", parsedDate.value, workforceDeploymentContext, ["WORKFORCE_DEPLOYMENT_CONTRACT_UNSUPPORTED"]);
    if (workforceDeploymentContext.status !== "READY" || !workforceDeploymentContext.contract || workforceDeploymentContext.contract.sourceProfile !== Authority.CONTRACT.PROFILES.WORKFORCE_DEPLOYMENT_V2) return emptyContext("UNAVAILABLE", parsedDate.value, workforceDeploymentContext, ["WORKFORCE_DEPLOYMENT_CONTEXT_UNAVAILABLE"]);
    const source = Array.isArray(workforceDeploymentContext.records) ? workforceDeploymentContext.records : []; const effective = source.filter((record) => isEffective(record, parsedDate.value)); const byEmployee = new Map(); const byBranch = new Map(); const primary = new Map(); const support = new Map(); const conflicts = new Set();
    effective.forEach((record) => { if (!byEmployee.has(record.employeeId)) byEmployee.set(record.employeeId, []); byEmployee.get(record.employeeId).push(record); if (!byBranch.has(record.branchId)) byBranch.set(record.branchId, []); byBranch.get(record.branchId).push(record); if (record.deploymentType === "PRIMARY") { if (primary.has(record.branchId)) conflicts.add(record.branchId); else primary.set(record.branchId, record); } else if (record.deploymentType === "SUPPORT") { if (!support.has(record.branchId)) support.set(record.branchId, []); support.get(record.branchId).push(record); } });
    conflicts.forEach((branchId) => primary.set(branchId, null)); const employeeIndex = freezeIndex(byEmployee); const branchIndex = freezeIndex(byBranch); const supportIndex = freezeIndex(support); const coverage = Object.freeze({ totalCanonicalDeployments: source.length, effectiveDeployments: effective.length, employeesRepresented: employeeIndex.size, branchesRepresented: branchIndex.size, branchesWithPrimary: [...primary.entries()].filter(([, item]) => item).length, branchesWithSupport: supportIndex.size, branchesWithNoPrimary: [...branchIndex.keys()].filter((branchId) => !primary.get(branchId)).length, employeesWithMultipleEffectiveBranches: [...employeeIndex.values()].filter((records) => new Set(records.map((record) => record.branchId)).size > 1).length }); const diagnostics = conflicts.size ? ["WORKFORCE_DEPLOYMENT_PRIMARY_CONFLICT"] : []; return Object.freeze({ status: conflicts.size ? "INVALID" : "READY", asOfDate: parsedDate.value, sourceContext: workforceDeploymentContext, deploymentCount: source.length, effectiveDeploymentCount: effective.length, employeeCount: employeeIndex.size, branchCount: branchIndex.size, deploymentsByEmployee: employeeIndex, deploymentsByBranch: branchIndex, primaryByBranch: primary, supportByBranch: supportIndex, primaryConflictBranchIds: conflicts, coverage, diagnostics: Object.freeze(diagnostics) });
  }
  function resolveEmployee(employeeId, context) { const id = Authority.normalizeCode(employeeId); if (!context || !["READY", "INVALID"].includes(context.status)) return Object.freeze({ status: context && context.status || "UNAVAILABLE", employeeId: id, asOfDate: context && context.asOfDate || null, deployments: Object.freeze([]), diagnostics: context && context.diagnostics || Object.freeze([]) }); const deployments = context.deploymentsByEmployee.get(id) || Object.freeze([]); return Object.freeze({ status: deployments.length ? "RESOLVED" : "NO_DEPLOYMENT", employeeId: id, asOfDate: context.asOfDate, deployments, diagnostics: Object.freeze([]) }); }
  function resolveBranch(branchId, context) { const id = Authority.normalizeText(branchId); if (!context || !["READY", "INVALID"].includes(context.status)) return Object.freeze({ status: context && context.status || "UNAVAILABLE", branchId: id, asOfDate: context && context.asOfDate || null, deployments: Object.freeze([]), primary: null, support: Object.freeze([]), diagnostics: context && context.diagnostics || Object.freeze([]) }); const deployments = context.deploymentsByBranch.get(id) || Object.freeze([]); const conflict = context.primaryConflictBranchIds.has(id); return Object.freeze({ status: !deployments.length ? "NO_DEPLOYMENT" : conflict ? "PRIMARY_CONFLICT" : "RESOLVED", branchId: id, asOfDate: context.asOfDate, deployments, primary: conflict ? null : context.primaryByBranch.get(id) || null, support: context.supportByBranch.get(id) || Object.freeze([]), diagnostics: Object.freeze(conflict ? ["WORKFORCE_DEPLOYMENT_PRIMARY_CONFLICT"] : []) }); }
  function getPrimary(branchId, context) { const result = resolveBranch(branchId, context); return Object.freeze({ status: result.status, deployment: result.primary, diagnostics: result.diagnostics }); }
  function getSupport(branchId, context) { return resolveBranch(branchId, context).support; }
  function summarize(context) { return Object.freeze({ status: context && context.status || "UNAVAILABLE", asOfDate: context && context.asOfDate || null, coverage: context && context.coverage || emptyContext("UNAVAILABLE").coverage, diagnostics: context && context.diagnostics || Object.freeze([]) }); }
  global.BancaTrackerWorkforceDeploymentResolver = Object.freeze({ createContext, resolveEmployee, resolveBranch, getPrimary, getSupport, summarize });
})(window);
