/* Activation renderer consuming current-period derived metrics from the central scope context. */
(function (global) {
  const config = global.BancaTrackerConfig; const utils = global.BancaTrackerUtils; const LIMIT = 100;
  const BAND_ORDER = ["Zero", "1 - 14.9K", "15K - 24.9K", "25K - 49.9K", "50K - 99.9K", "1L - 1.99L", "2L+"];
  function renderKpis(d) { const cards = [["Observed Branches (Current Period)", d.branches.length], ["Active Branches (Current Period)", d.activeBranches.length], ["Near Active Branches (Current Period)", d.nearActiveBranches.length], ["Current Period Premium", utils.formatInr(d.totalPremium)]]; document.getElementById("activationKpis").innerHTML = cards.map(([label, value]) => `<div class='card'><div>${label}</div><div class='value'>${value}</div></div>`).join(""); }
  function renderMaturity(d) { document.getElementById("branchPyramid").innerHTML = BAND_ORDER.map((band) => `<div class='metric'><strong>${band}</strong>: ${d.branchBands[band] || 0}</div>`).join(""); }
  function renderOpportunities(d) { const all = [...d.nearActiveBranches].sort((a, b) => (config.THRESHOLDS.ACTIVE_BRANCH - a.premium) - (config.THRESHOLDS.ACTIVE_BRANCH - b.premium)); const shown = all.slice(0, LIMIT); const container = document.getElementById("opportunityBranches"); document.getElementById("opportunityCount").textContent = `${utils.formatInr(all.length)} near-active branch${all.length === 1 ? "" : "es"} in the current period${all.length > LIMIT ? `; showing first ${LIMIT}` : ""}`; if (!all.length) { container.innerHTML = "<p class='empty-state'>No near-active branches in the current period.</p>"; return; } container.innerHTML = `<table><thead><tr><th>Branch</th><th>Bank</th><th>Zone</th><th>State</th><th>Current Period Premium</th><th>Gap To ₹25K</th></tr></thead><tbody>${shown.map((branch) => `<tr><td>${utils.escapeHtml(branch.branch)}</td><td>${utils.escapeHtml(branch.bank)}</td><td>${utils.escapeHtml(branch.zone || "Unknown")}</td><td>${utils.escapeHtml(branch.state || "Unknown")}</td><td>${utils.formatInr(branch.premium)}</td><td>${utils.formatInr(config.THRESHOLDS.ACTIVE_BRANCH - branch.premium)}</td></tr>`).join("")}</tbody></table>`; }
  function buildBankMetrics(d, universeResult) {
    const authority = global.BancaTrackerLiveBranchUniverseAuthority;
    const universe = universeResult || (authority && authority.getUniverse());
    const governedBanks = universe && universe.authority === "GOVERNED" ? Object.keys(universe.governed.byBank) : [];
    const banks = [...new Set([...Object.keys(config.TOTAL_BRANCHES), ...governedBanks, ...Object.keys(d.bankBranchMetrics)])];
    return banks.map((bank) => {
      const denominator = authority
        ? authority.getBankUniverse(bank, universe)
        : Object.prototype.hasOwnProperty.call(config.TOTAL_BRANCHES, bank) ? config.TOTAL_BRANCHES[bank] : null;
      const active = (d.bankBranchMetrics[bank] || {}).active || 0;
      return { bank, active, denominator, activationPercent: denominator ? (active / denominator) * 100 : null };
    });
  }
  function renderBanks(d) { const authority = global.BancaTrackerLiveBranchUniverseAuthority; const universe = authority && authority.getUniverse(); const rows = buildBankMetrics(d, universe); const label = universe && universe.authority === "GOVERNED" ? "Governed eligible Branch Master universe" : "Legacy configured branch universe"; document.getElementById("bankActivation").innerHTML = `<p class='activation-note'>${label} is the denominator; active counts use current-period uploaded records.</p><table><thead><tr><th>Bank</th><th>Active Branches</th><th>Branch Universe</th><th>Activation %</th></tr></thead><tbody>${rows.map((item) => `<tr><td>${utils.escapeHtml(item.bank)}</td><td>${item.active}</td><td>${item.denominator === null ? "Not configured" : item.denominator}</td><td>${item.activationPercent === null ? "N/A" : `${item.activationPercent.toFixed(1)}%`}</td></tr>`).join("")}</tbody></table>`; }
  function renderLocations(locations, label, id, emptyMessage) { const container = document.getElementById(id); const entries = Object.entries(locations).sort((a, b) => b[1].premium - a[1].premium); if (!entries.length) { container.innerHTML = `<p class='empty-state'>${emptyMessage}</p>`; return; } const note = entries.length > LIMIT ? `<p class='table-limit-note'>Showing top ${LIMIT} of ${utils.formatInr(entries.length)} results.</p>` : ""; container.innerHTML = `${note}<table><thead><tr><th>${label}</th><th>Current Period Premium</th><th>Active Branches</th><th>Observed Branches</th><th>Activation % (Observed)</th></tr></thead><tbody>${entries.slice(0, LIMIT).map(([name, m]) => `<tr><td>${utils.escapeHtml(name)}</td><td>${utils.formatInr(m.premium)}</td><td>${m.active}</td><td>${m.total}</td><td>${utils.formatPercent(m.active, m.total)}</td></tr>`).join("")}</tbody></table>`; }
  function refreshActivation(d) { const context = global.BancaTrackerCore.getPerformanceContext(); const filters = global.BancaTrackerCore.state.filters; const authority = global.BancaTrackerLiveBranchUniverseAuthority; const authorityLabel = authority && authority.getAuthorityStatus() === "GOVERNED" ? "governed eligible Branch Master universe" : "legacy configured branch universe"; document.getElementById("activationScope").textContent = `Activation scope: ${context.currentPeriodMonth || "No configured fiscal month available"}; Bank: ${filters.bank}. Active, near-active, maturity, opportunity, Zone and State metrics use current-period uploaded records. Bank Activation % uses ${authorityLabel}; Zone/State Activation % uses observed branches.${context.currentPeriodIsUnconfigured ? " The selected month is unconfigured and is excluded from fiscal YTD and target progression." : ""}`; renderKpis(d); renderMaturity(d); renderBanks(d); renderOpportunities(d); renderLocations(d.zones, "Zone", "zoneActivation", "No zone data supplied in the current period."); renderLocations(d.states, "State", "stateActivation", "No state data supplied in the current period."); }
  global.BancaTrackerActivation = Object.freeze({ buildBankMetrics, refreshActivation }); global.refreshActivation = refreshActivation;
})(window);
