/* Activation renderer consuming the shared per-refresh derived metrics. */
(function (global) {
  const config = global.BancaTrackerConfig; const utils = global.BancaTrackerUtils; const LIMIT = 100;
  const BAND_ORDER = ["Zero", "1 - 14.9K", "15K - 24.9K", "25K - 49.9K", "50K - 99.9K", "1L - 1.99L", "2L+"];
  function renderKpis(d) { const cards = [["Observed Branches", d.branches.length], ["Active Branches", d.activeBranches.length], ["Near Active Branches", d.nearActiveBranches.length], ["Observed Premium", utils.formatInr(d.totalPremium)]]; document.getElementById("activationKpis").innerHTML = cards.map(([label, value]) => `<div class='card'><div>${label}</div><div class='value'>${value}</div></div>`).join(""); }
  function renderMaturity(d) { document.getElementById("branchPyramid").innerHTML = BAND_ORDER.map((band) => `<div class='metric'><strong>${band}</strong>: ${d.branchBands[band] || 0}</div>`).join(""); }
  function renderOpportunities(d) { const all = [...d.nearActiveBranches].sort((a, b) => (config.THRESHOLDS.ACTIVE_BRANCH - a.premium) - (config.THRESHOLDS.ACTIVE_BRANCH - b.premium)); const shown = all.slice(0, LIMIT); const container = document.getElementById("opportunityBranches"); document.getElementById("opportunityCount").textContent = `${utils.formatInr(all.length)} near-active branch${all.length === 1 ? "" : "es"} in the selected view${all.length > LIMIT ? `; showing first ${LIMIT}` : ""}`; if (!all.length) { container.innerHTML = "<p class='empty-state'>No near-active branches in the selected view.</p>"; return; } container.innerHTML = `<table><thead><tr><th>Branch</th><th>Bank</th><th>Zone</th><th>State</th><th>Current Premium</th><th>Gap To ₹25K</th></tr></thead><tbody>${shown.map((branch) => `<tr><td>${utils.escapeHtml(branch.branch)}</td><td>${utils.escapeHtml(branch.bank)}</td><td>${utils.escapeHtml(branch.zone || "Unknown")}</td><td>${utils.escapeHtml(branch.state || "Unknown")}</td><td>${utils.formatInr(branch.premium)}</td><td>${utils.formatInr(config.THRESHOLDS.ACTIVE_BRANCH - branch.premium)}</td></tr>`).join("")}</tbody></table>`; }
  function renderBanks(d) { const banks = [...new Set([...Object.keys(config.TOTAL_BRANCHES), ...Object.keys(d.bankBranchMetrics)])]; document.getElementById("bankActivation").innerHTML = `<p class='activation-note'>Configured universe is the denominator; branch counts are observed in the selected view.</p><table><thead><tr><th>Bank</th><th>Active Branches</th><th>Branch Universe</th><th>Activation %</th></tr></thead><tbody>${banks.map((bank) => { const universe = config.TOTAL_BRANCHES[bank]; const active = (d.bankBranchMetrics[bank] || {}).active || 0; return `<tr><td>${utils.escapeHtml(bank)}</td><td>${active}</td><td>${universe || "Not configured"}</td><td>${universe ? utils.formatPercent(active, universe) : "N/A"}</td></tr>`; }).join("")}</tbody></table>`; }
  function renderLocations(locations, label, id, emptyMessage) { const container = document.getElementById(id); const entries = Object.entries(locations).sort((a, b) => b[1].premium - a[1].premium); if (!entries.length) { container.innerHTML = `<p class='empty-state'>${emptyMessage}</p>`; return; } const note = entries.length > LIMIT ? `<p class='table-limit-note'>Showing top ${LIMIT} of ${utils.formatInr(entries.length)} results.</p>` : ""; container.innerHTML = `${note}<table><thead><tr><th>${label}</th><th>Premium</th><th>Active Branches</th><th>Observed Branches</th><th>Activation %</th></tr></thead><tbody>${entries.slice(0, LIMIT).map(([name, m]) => `<tr><td>${utils.escapeHtml(name)}</td><td>${utils.formatInr(m.premium)}</td><td>${m.active}</td><td>${m.total}</td><td>${utils.formatPercent(m.active, m.total)}</td></tr>`).join("")}</tbody></table>`; }
  function refreshActivation(d) { const filters = global.BancaTrackerCore.state.filters; document.getElementById("activationScope").textContent = `Current scope — Month: ${filters.month}; Bank: ${filters.bank}. Branch counts are based only on uploaded records in this scope.`; renderKpis(d); renderMaturity(d); renderBanks(d); renderOpportunities(d); renderLocations(d.zones, "Zone", "zoneActivation", "No zone data supplied in the selected view."); renderLocations(d.states, "State", "stateActivation", "No state data supplied in the selected view."); }
  global.BancaTrackerActivation = Object.freeze({ refreshActivation }); global.refreshActivation = refreshActivation;
})(window);
