/* Current-period productivity and opportunity intelligence using central context and canonical branches. */
(function (global) {
  const config = global.BancaTrackerConfig; const utils = global.BancaTrackerUtils;
  const LIMITS = { rm: 50, imd: 50, branch: 100, opportunity: 100 };
  const clean = (value) => String(value == null ? "" : value).trim();
  const addSet = (set, value) => { if (clean(value)) set.add(clean(value)); };
  function entityBase(key, bank, code) { return { key, bank, code, premium: 0, records: 0, branchKeys: new Set(), names: new Set(), lobs: new Set(), productCodes: new Set(), baCodes: new Set() }; }
  function branchStatus(branch) { return { active: branch.premium >= config.THRESHOLDS.ACTIVE_BRANCH, near: branch.premium >= config.THRESHOLDS.NEAR_ACTIVE_MIN && branch.premium < config.THRESHOLDS.ACTIVE_BRANCH }; }
  function singleOr(values, blankLabel) { const list = [...values]; return list.length === 0 ? blankLabel : list.length === 1 ? list[0] : "Multiple mappings"; }
  function finalizeEntity(entity, derived, kind, audit) {
    let activeBranches = 0; let nearActiveBranches = 0; let aggregateActivationGap = 0;
    entity.branchKeys.forEach((key) => { const branch = derived.branchesByKey[key]; if (!branch) return; const status = branchStatus(branch); if (status.active) activeBranches += 1; if (status.near) { nearActiveBranches += 1; aggregateActivationGap += config.THRESHOLDS.ACTIVE_BRANCH - branch.premium; } });
    const observedBranches = entity.branchKeys.size;
    const mappingConflict = kind === "rm" && (entity.names.size > 1 || audit.baCodeConflicts.some((item) => item.key === entity.code));
    const premiumPerObservedBranch = observedBranches ? entity.premium / observedBranches : null;
    const premiumPerActiveBranch = activeBranches ? entity.premium / activeBranches : null;
    let cue = "";
    if (nearActiveBranches > 0) cue = kind === "imd" ? "High activation-conversion opportunity." : "Prioritize near-active branch conversion.";
    else if (kind === "rm" && entity.premium > 0 && activeBranches > 0 && activeBranches < observedBranches) cue = "Premium concentrated in fewer active branches.";
    return { ...entity, name: mappingConflict ? "Mapping conflict" : singleOr(entity.names, "Not mapped"), mappingConflict, observedBranches, activeBranches, nearActiveBranches, aggregateActivationGap, premiumPerObservedBranch, premiumPerActiveBranch, lobBreadth: entity.lobs.size, productBreadth: entity.productCodes.size, observedBaCodes: entity.baCodes.size, cue };
  }
  function concentration(opportunities, dimension, label) {
    const map = new Map();
    opportunities.forEach((branch) => {
      const name = dimension(branch);
      if (!map.has(name)) map.set(name, { dimension: label, name, nearActiveBranches: 0, aggregateGap: 0 });
      const item = map.get(name); item.nearActiveBranches += 1; item.aggregateGap += config.THRESHOLDS.ACTIVE_BRANCH - branch.premium;
    });
    return [...map.values()].sort((a, b) => b.nearActiveBranches - a.nearActiveBranches || b.aggregateGap - a.aggregateGap || a.name.localeCompare(b.name));
  }
  function build(context, derived, audit) {
    const quality = audit || { baCodeConflicts: [], hierarchyConflicts: [], productConflicts: [], bankQuality: { unknownBanks: [] } };
    const rms = new Map(); const imds = new Map(); const businessTypes = new Map();
    context.currentPeriodData.forEach((row) => {
      const branchKey = utils.branchIdentityKey(row);
      if (clean(row.baCode)) { const key = `${row.bank}::${row.baCode}`; if (!rms.has(key)) rms.set(key, entityBase(key, row.bank, row.baCode)); const item = rms.get(key); item.premium += row.premium; item.records += 1; if (branchKey) item.branchKeys.add(branchKey); addSet(item.names, row.rm); addSet(item.lobs, row.lob); addSet(item.productCodes, row.productCode); }
      if (clean(row.imd)) { const key = `${row.bank}::${row.imd}`; if (!imds.has(key)) imds.set(key, entityBase(key, row.bank, row.imd)); const item = imds.get(key); item.premium += row.premium; item.records += 1; if (branchKey) item.branchKeys.add(branchKey); addSet(item.baCodes, row.baCode); addSet(item.lobs, row.lob); addSet(item.productCodes, row.productCode); }
      const businessType = clean(row.businessType) || "Unknown"; businessTypes.set(businessType, (businessTypes.get(businessType) || 0) + row.premium);
    });
    const rmMetrics = [...rms.values()].map((item) => finalizeEntity(item, derived, "rm", quality)).sort((a, b) => b.premium - a.premium || a.code.localeCompare(b.code));
    const imdMetrics = [...imds.values()].map((item) => finalizeEntity(item, derived, "imd", quality)).sort((a, b) => b.premium - a.premium || a.code.localeCompare(b.code));
    const hierarchyConflictKeys = new Set(quality.hierarchyConflicts.map((item) => item.branchKey));
    const productConflictCodes = new Set(quality.productConflicts.map((item) => item.key));
    const unknownBanks = new Set(quality.bankQuality.unknownBanks);
    const branchMetrics = derived.branches.map((branch) => {
      const status = branchStatus(branch); const gap = Math.max(0, config.THRESHOLDS.ACTIVE_BRANCH - branch.premium);
      return { ...branch, zoneLabel: singleOr(branch.zones, "Not mapped"), stateLabel: singleOr(branch.states, "Not mapped"), baCodeLabel: singleOr(branch.baCodes, "Not mapped"), rmLabel: singleOr(branch.rmNames, "Not mapped"), imdLabel: singleOr(branch.imds, "Not mapped"), maturityBand: utils.getBranchBand(branch.premium), active: status.active, nearActive: status.near, gap, lobBreadth: branch.lobs.size, productBreadth: branch.productCodes.size, hierarchyConflict: hierarchyConflictKeys.has(branch.key), productMappingConflict: [...branch.productCodes].some((code) => productConflictCodes.has(code)), unknownBank: unknownBanks.has(branch.bank), cue: status.near && gap <= 5000 ? "Immediate activation opportunity." : status.near ? "Near-active conversion opportunity." : "" };
    }).sort((a, b) => b.premium - a.premium || a.branch.localeCompare(b.branch));
    const opportunities = branchMetrics.filter((branch) => branch.nearActive).sort((a, b) => a.gap - b.gap || b.premium - a.premium);
    const ownerRm = (branch) => branch.baCodes.size === 1 ? `${[...branch.baCodes][0]} / ${branch.rmNames.size === 1 ? [...branch.rmNames][0] : branch.rmNames.size > 1 ? "Mapping conflict" : "Not mapped"}` : branch.baCodes.size > 1 ? "Multiple mappings" : "Not mapped";
    const ownerImd = (branch) => branch.imds.size === 1 ? `${branch.bank} / ${[...branch.imds][0]}` : branch.imds.size > 1 ? "Multiple mappings" : "Not mapped";
    const concentrations = {
      bank: concentration(opportunities, (branch) => branch.bank, "Bank"), zone: concentration(opportunities, (branch) => branch.zoneLabel, "Zone"), state: concentration(opportunities, (branch) => branch.stateLabel, "State"), rm: concentration(opportunities, ownerRm, "BA Code / RM"), imd: concentration(opportunities, ownerImd, "Bank / IMD")
    };
    const productCompleteness = quality.completeness ? quality.completeness.find((item) => item.field === "productCode") : null;
    const ytdPremiumByBank = context.ytdPremiumByBank;
    const bankIndexes = {};
    const ensureBank = (bank) => bankIndexes[bank] || (bankIndexes[bank] = { rms: [], imds: [], branches: [], opportunities: [] });
    rmMetrics.forEach((item) => ensureBank(item.bank).rms.push(item)); imdMetrics.forEach((item) => ensureBank(item.bank).imds.push(item)); branchMetrics.forEach((item) => ensureBank(item.bank).branches.push(item)); opportunities.forEach((item) => ensureBank(item.bank).opportunities.push(item));
    return { scopeMonth: context.currentPeriodMonth, scopeIsUnconfigured: context.currentPeriodIsUnconfigured, rmMetrics, imdMetrics, branchMetrics, opportunities, concentrations, bankIndexes, ytdPremiumByBank, businessTypes: [...businessTypes.entries()].map(([name, premium]) => ({ name, premium })).sort((a, b) => b.premium - a.premium), productCodeCompleteness: productCompleteness ? productCompleteness.completenessPercent : null, summary: { observedBaCodes: rmMetrics.length, observedImds: imdMetrics.length, observedBranches: branchMetrics.length, activeBranches: derived.activeBranches.length, nearActiveBranches: opportunities.length, aggregateActivationGap: opportunities.reduce((sum, branch) => sum + branch.gap, 0) } };
  }

  const html = (value) => utils.escapeHtml(value); const amount = (value) => value == null ? "—" : utils.formatInr(value);
  const limitNote = (count, limit) => count > limit ? `<p class='table-limit-note'>Showing top ${limit} of ${utils.formatInr(count)} results.</p>` : "";
  function renderEntityTable(items, kind) { const limit = LIMITS[kind]; if (!items.length) return "<p class='empty-state'>No mapped entities in the current period.</p>"; const isRm = kind === "rm"; return `${limitNote(items.length, limit)}<table><thead><tr><th>${isRm ? "BA Code" : "IMD Code"}</th>${isRm ? "<th>RM Name</th>" : ""}<th>Bank</th><th>Premium</th><th>Observed Branches</th><th>Active</th><th>Near Active</th><th>${isRm ? "Records" : "Observed BA Codes"}</th>${!isRm ? "<th>Records</th>" : ""}<th>Premium / Observed Branch</th>${isRm ? "<th>Premium / Active Branch</th>" : ""}<th>LOB Breadth</th><th>Product Breadth</th><th>Management Cue</th></tr></thead><tbody>${items.slice(0, limit).map((item) => `<tr><td>${html(item.code)}</td>${isRm ? `<td>${html(item.name)}${item.mappingConflict ? " <span class='quality-severity quality-warning'>WARNING</span>" : ""}</td>` : ""}<td>${html(item.bank)}</td><td>${amount(item.premium)}</td><td>${item.observedBranches}</td><td>${item.activeBranches}</td><td>${item.nearActiveBranches}</td><td>${isRm ? item.records : item.observedBaCodes}</td>${!isRm ? `<td>${item.records}</td>` : ""}<td>${amount(item.premiumPerObservedBranch)}</td>${isRm ? `<td>${amount(item.premiumPerActiveBranch)}</td>` : ""}<td>${item.lobBreadth}</td><td>${item.productBreadth}</td><td>${html(item.cue || "—")}</td></tr>`).join("")}</tbody></table>`; }
  function renderBranches(items) { if (!items.length) return "<p class='empty-state'>No observed branches in the current period.</p>"; return `${limitNote(items.length, LIMITS.branch)}<table><thead><tr><th>Branch</th><th>Bank</th><th>Zone</th><th>State</th><th>RM / BA Code</th><th>IMD</th><th>Premium</th><th>Maturity</th><th>Gap to ₹25K</th><th>LOB Breadth</th><th>Product Breadth</th><th>Quality</th></tr></thead><tbody>${items.slice(0, LIMITS.branch).map((branch) => `<tr><td>${html(branch.branch)}</td><td>${html(branch.bank)}</td><td>${html(branch.zoneLabel)}</td><td>${html(branch.stateLabel)}</td><td>${html(`${branch.rmLabel} / ${branch.baCodeLabel}`)}</td><td>${html(branch.imdLabel)}</td><td>${amount(branch.premium)}</td><td>${html(branch.maturityBand)}</td><td>${branch.active ? "Active" : amount(branch.gap)}</td><td>${branch.lobBreadth}</td><td>${branch.productBreadth}</td><td>${html([branch.hierarchyConflict ? "Hierarchy conflict" : "", branch.productMappingConflict ? "Product mapping conflict" : "", branch.unknownBank ? "Unknown bank" : ""].filter(Boolean).join("; ") || "—")}</td></tr>`).join("")}</tbody></table>`; }
  function renderOpportunities(items) { if (!items.length) return "<p class='empty-state'>No near-active opportunities in the current period.</p>"; return `${limitNote(items.length, LIMITS.opportunity)}<table><thead><tr><th>Branch</th><th>Bank</th><th>Zone</th><th>State</th><th>BA Code</th><th>RM Name</th><th>IMD</th><th>Current Premium</th><th>Gap to ₹25K</th><th>Cue</th></tr></thead><tbody>${items.slice(0, LIMITS.opportunity).map((branch) => `<tr><td>${html(branch.branch)}</td><td>${html(branch.bank)}</td><td>${html(branch.zoneLabel)}</td><td>${html(branch.stateLabel)}</td><td>${html(branch.baCodeLabel)}</td><td>${html(branch.rmLabel)}</td><td>${html(branch.imdLabel)}</td><td>${amount(branch.premium)}</td><td>${amount(branch.gap)}</td><td>${html(branch.cue)}</td></tr>`).join("")}</tbody></table>`; }
  function renderConcentration(groups) { return Object.entries(groups).map(([key, items]) => `<div class='panel'><h3>${html(items[0] ? items[0].dimension : key)}</h3>${items.length ? `${limitNote(items.length, 50)}<table><thead><tr><th>Group</th><th>Near Active Branches</th><th>Aggregate Activation Gap</th></tr></thead><tbody>${items.slice(0, 50).map((item) => `<tr><td>${html(item.name)}</td><td>${item.nearActiveBranches}</td><td>${amount(item.aggregateGap)}</td></tr>`).join("")}</tbody></table>` : "<p class='empty-state'>No near-active opportunities.</p>"}</div>`).join(""); }
  function render(result) { if (!result) return; const s = result.summary; const productNote = result.productCodeCompleteness == null ? " Product Code completeness is unavailable." : ` Full-upload Product Code completeness is ${result.productCodeCompleteness.toFixed(1)}%; breadth counts only populated codes.`; const unconfiguredNote = result.scopeIsUnconfigured ? " This selected month is unconfigured and is excluded from fiscal YTD and target elapsed months." : ""; document.getElementById("productivityScope").textContent = `Productivity and opportunity scope: ${result.scopeMonth || "No configured fiscal month available"} (CURRENT PERIOD). Month and Bank filters apply. Activation and premium shown together use the same period.${productNote}${unconfiguredNote}`; document.getElementById("productivitySummary").innerHTML = [["Observed BA Codes", s.observedBaCodes], ["Observed IMDs", s.observedImds], ["Observed Branches", s.observedBranches], ["Active Branches", s.activeBranches], ["Near Active Branches", s.nearActiveBranches], ["Aggregate Activation Gap", utils.formatInr(s.aggregateActivationGap)]].map(([label, value]) => `<div class='card'><div>${label}</div><div class='value'>${value}</div></div>`).join(""); document.getElementById("rmProductivity").innerHTML = renderEntityTable(result.rmMetrics, "rm"); document.getElementById("imdProductivity").innerHTML = renderEntityTable(result.imdMetrics, "imd"); document.getElementById("branchProductivity").innerHTML = renderBranches(result.branchMetrics); document.getElementById("opportunityOwnership").innerHTML = renderOpportunities(result.opportunities); document.getElementById("opportunityConcentration").innerHTML = renderConcentration(result.concentrations); document.getElementById("businessTypeSplit").innerHTML = result.businessTypes.length ? `<table><thead><tr><th>Source Business Type</th><th>Current Period Premium</th></tr></thead><tbody>${result.businessTypes.map((item) => `<tr><td>${html(item.name)}</td><td>${amount(item.premium)}</td></tr>`).join("")}</tbody></table>` : "<p class='empty-state'>No Business Type values in the current period.</p>"; }
  global.BancaTrackerProductivity = Object.freeze({ build, render, concentration, LIMITS }); global.renderProductivity = render;
})(window);
